/**
 * Motion preset registry — named animation recipes that themes + sections
 * reference by id. Each preset declares CSS-keyframe-friendly state pairs
 * (initial/animate) plus timing. The wirer compiles these into a Tailwind
 * plugin entry at render time so Studio can pick from a fixed gallery.
 *
 * Phase 5 wave 1 ships a foundational set covering enter, exit, attention,
 * and continuous-loop intents. Wave 2 adds page-transition + hover-driven
 * presets.
 */
import { z } from 'zod'

export const MOTION_INTENT = [
  'enter',     // first-paint reveal
  'exit',      // dismiss / leave
  'attention', // pulse / shake / wiggle to draw eyes
  'loop',      // continuous animation (spinner, marquee)
] as const

export const MOTION_KEY = [
  'opacity',
  'transform',
  'translate',
  'scale',
  'rotate',
] as const

export const MotionPresetSchema = z.object({
  /** kebab-case preset id, e.g. "fade-in-up". */
  id: z.string().regex(/^[a-z][a-z0-9-]*$/),
  displayName: z.string().min(1),
  intent: z.enum(MOTION_INTENT),
  /** Initial style state — CSS prop → value (string). */
  from: z.record(z.string()),
  /** End state. Reached via the configured easing + duration. */
  to: z.record(z.string()),
  /** Duration (ms). Honors the theme's motion.duration map at render. */
  durationMs: z.number().int().positive().default(320),
  /** Cubic-bezier easing or named keyword. */
  easing: z.string().default('cubic-bezier(0.4, 0, 0.2, 1)'),
  /** ms delay before the animation kicks. */
  delayMs: z.number().int().nonnegative().default(0),
  /** For intent=loop: ``infinite`` runs forever. */
  iterations: z.union([z.number().int().positive(), z.literal('infinite')])
    .default(1),
  /** Tailwind animation utility class to emit, e.g. "animate-fade-in-up". */
  className: z.string().min(1),
})

export type MotionIntent = (typeof MOTION_INTENT)[number]
export type MotionKey = (typeof MOTION_KEY)[number]
export type MotionPreset = z.infer<typeof MotionPresetSchema>


/** Built-in catalog. Operators can ship more via theme packs. */
export const MOTION_PRESET_CATALOG: Record<string, MotionPreset> = {
  'fade-in': {
    id: 'fade-in',
    displayName: 'Fade in',
    intent: 'enter',
    from: { opacity: '0' },
    to: { opacity: '1' },
    durationMs: 320,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in',
  },
  'fade-in-up': {
    id: 'fade-in-up',
    displayName: 'Fade in (up)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 360,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-up',
  },
  'fade-in-down': {
    id: 'fade-in-down',
    displayName: 'Fade in (down)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-8px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 360,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-down',
  },
  'slide-in-left': {
    id: 'slide-in-left',
    displayName: 'Slide in (from left)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(-16px)' },
    to: { opacity: '1', transform: 'translateX(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-in-left',
  },
  'slide-in-right': {
    id: 'slide-in-right',
    displayName: 'Slide in (from right)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(16px)' },
    to: { opacity: '1', transform: 'translateX(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-in-right',
  },
  'scale-in': {
    id: 'scale-in',
    displayName: 'Scale in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.96)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-scale-in',
  },
  'fade-out': {
    id: 'fade-out',
    displayName: 'Fade out',
    intent: 'exit',
    from: { opacity: '1' },
    to: { opacity: '0' },
    durationMs: 200,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-out',
  },
  'pulse': {
    id: 'pulse',
    displayName: 'Pulse',
    intent: 'attention',
    from: { opacity: '1' },
    to: { opacity: '0.4' },
    durationMs: 1500,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-pulse-soft',
  },
  'shake': {
    id: 'shake',
    displayName: 'Shake',
    intent: 'attention',
    from: { transform: 'translateX(-4px)' },
    to: { transform: 'translateX(4px)' },
    durationMs: 80,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 6,
    className: 'animate-shake',
  },
  'spin-slow': {
    id: 'spin-slow',
    displayName: 'Spin (slow)',
    intent: 'loop',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
    durationMs: 4000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-spin-slow',
  },
  // ---- Wave 2: 10 more ----
  'fade-in-left': {
    id: 'fade-in-left',
    displayName: 'Fade in (from left)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(-16px)' },
    to: { opacity: '1', transform: 'translateX(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-left',
  },
  'fade-in-right': {
    id: 'fade-in-right',
    displayName: 'Fade in (from right)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(16px)' },
    to: { opacity: '1', transform: 'translateX(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-right',
  },
  'zoom-in': {
    id: 'zoom-in',
    displayName: 'Zoom in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.85)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-zoom-in',
  },
  'zoom-out': {
    id: 'zoom-out',
    displayName: 'Zoom out',
    intent: 'exit',
    from: { opacity: '1', transform: 'scale(1)' },
    to: { opacity: '0', transform: 'scale(0.85)' },
    durationMs: 260,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-zoom-out',
  },
  'bounce': {
    id: 'bounce',
    displayName: 'Bounce',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-12px)' },
    durationMs: 600,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-bounce-soft',
  },
  'wobble': {
    id: 'wobble',
    displayName: 'Wobble',
    intent: 'attention',
    from: { transform: 'rotate(-3deg)' },
    to: { transform: 'rotate(3deg)' },
    durationMs: 140,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 5,
    className: 'animate-wobble',
  },
  'pop': {
    id: 'pop',
    displayName: 'Pop',
    intent: 'attention',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.08)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-pop',
  },
  'slide-up': {
    id: 'slide-up',
    displayName: 'Slide up',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(24px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 420,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-up',
  },
  'slide-down': {
    id: 'slide-down',
    displayName: 'Slide down',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-24px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 420,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-down',
  },
  'spin-fast': {
    id: 'spin-fast',
    displayName: 'Spin (fast)',
    intent: 'loop',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
    durationMs: 900,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-spin-fast',
  },
  // ---- Wave 3: 10 more ----
  'typing-cursor': {
    id: 'typing-cursor',
    displayName: 'Typing cursor blink',
    intent: 'loop',
    from: { opacity: '1' },
    to: { opacity: '0' },
    durationMs: 600,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-typing-cursor',
  },
  'heartbeat': {
    id: 'heartbeat',
    displayName: 'Heartbeat',
    intent: 'loop',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.06)' },
    durationMs: 700,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-heartbeat',
  },
  'jiggle': {
    id: 'jiggle',
    displayName: 'Jiggle',
    intent: 'attention',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(2px)' },
    durationMs: 50,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 10,
    className: 'animate-jiggle',
  },
  'ripple': {
    id: 'ripple',
    displayName: 'Ripple',
    intent: 'attention',
    from: { opacity: '0.6', transform: 'scale(1)' },
    to: { opacity: '0', transform: 'scale(1.6)' },
    durationMs: 900,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-ripple',
  },
  'swing': {
    id: 'swing',
    displayName: 'Swing',
    intent: 'attention',
    from: { transform: 'rotate(-6deg)' },
    to: { transform: 'rotate(6deg)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-swing',
  },
  'flip-x': {
    id: 'flip-x',
    displayName: 'Flip (X axis)',
    intent: 'enter',
    from: { opacity: '0', transform: 'rotateX(-90deg)' },
    to: { opacity: '1', transform: 'rotateX(0deg)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-flip-x',
  },
  'flip-y': {
    id: 'flip-y',
    displayName: 'Flip (Y axis)',
    intent: 'enter',
    from: { opacity: '0', transform: 'rotateY(-90deg)' },
    to: { opacity: '1', transform: 'rotateY(0deg)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-flip-y',
  },
  'glide-in': {
    id: 'glide-in',
    displayName: 'Glide in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(40px) scale(0.96)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 560,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-glide-in',
  },
  'kenburns': {
    id: 'kenburns',
    displayName: 'Ken Burns (slow zoom)',
    intent: 'loop',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.08)' },
    durationMs: 9000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-kenburns',
  },
  'fade-up-stagger': {
    id: 'fade-up-stagger',
    displayName: 'Fade up (stagger child)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 240,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 60,
    iterations: 1,
    className: 'animate-fade-up-stagger',
  },
  // ---- Wave 4: 10 more ----
  'bounce-in': {
    id: 'bounce-in',
    displayName: 'Bounce in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.3)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-bounce-in',
  },
  'bounce-out': {
    id: 'bounce-out',
    displayName: 'Bounce out',
    intent: 'exit',
    from: { opacity: '1', transform: 'scale(1)' },
    to: { opacity: '0', transform: 'scale(0.3)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.36, 0, 0.66, -0.56)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-bounce-out',
  },
  'slide-in-up-stagger': {
    id: 'slide-in-up-stagger',
    displayName: 'Slide-in up (stagger)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(32px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 80,
    iterations: 1,
    className: 'animate-slide-in-up-stagger',
  },
  'blur-in': {
    id: 'blur-in',
    displayName: 'Blur in',
    intent: 'enter',
    from: { opacity: '0', filter: 'blur(12px)' },
    to: { opacity: '1', filter: 'blur(0)' },
    durationMs: 480,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-blur-in',
  },
  'focus-pulse': {
    id: 'focus-pulse',
    displayName: 'Focus pulse',
    intent: 'attention',
    from: { boxShadow: '0 0 0 0 rgba(59,130,246,0.5)' },
    to: { boxShadow: '0 0 0 8px rgba(59,130,246,0)' },
    durationMs: 1200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-focus-pulse',
  },
  'glow-pulse': {
    id: 'glow-pulse',
    displayName: 'Glow pulse',
    intent: 'attention',
    from: { boxShadow: '0 0 4px rgba(217,70,239,0.4)' },
    to: { boxShadow: '0 0 32px rgba(217,70,239,0.95)' },
    durationMs: 1600,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-glow-pulse',
  },
  'rotate-in': {
    id: 'rotate-in',
    displayName: 'Rotate in',
    intent: 'enter',
    from: { opacity: '0', transform: 'rotate(-180deg) scale(0.6)' },
    to: { opacity: '1', transform: 'rotate(0deg) scale(1)' },
    durationMs: 560,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-rotate-in',
  },
  'twist': {
    id: 'twist',
    displayName: 'Twist',
    intent: 'attention',
    from: { transform: 'rotate(-12deg) scale(0.96)' },
    to: { transform: 'rotate(12deg) scale(1.04)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-twist',
  },
  'shimmer': {
    id: 'shimmer',
    displayName: 'Shimmer (loading)',
    intent: 'loop',
    from: { backgroundPosition: '-200% 0' },
    to: { backgroundPosition: '200% 0' },
    durationMs: 1600,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-shimmer',
  },
  'draw-line': {
    id: 'draw-line',
    displayName: 'Draw line (SVG)',
    intent: 'enter',
    from: { strokeDashoffset: '1000' },
    to: { strokeDashoffset: '0' },
    durationMs: 1400,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-draw-line',
  },
  // ---- Wave 5: 10 more ----
  'tada': {
    id: 'tada',
    displayName: 'Tada',
    intent: 'attention',
    from: { transform: 'scale(1) rotate(0deg)' },
    to: { transform: 'scale(1.1) rotate(3deg)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 5,
    className: 'animate-tada',
  },
  'checkmark-draw': {
    id: 'checkmark-draw',
    displayName: 'Checkmark draw (SVG)',
    intent: 'enter',
    from: { strokeDashoffset: '48' },
    to: { strokeDashoffset: '0' },
    durationMs: 480,
    easing: 'cubic-bezier(0.65, 0, 0.45, 1)',
    delayMs: 80,
    iterations: 1,
    className: 'animate-checkmark-draw',
  },
  'cross-shake': {
    id: 'cross-shake',
    displayName: 'Cross shake (error)',
    intent: 'attention',
    from: { transform: 'translateX(-6px) rotate(-2deg)' },
    to: { transform: 'translateX(6px) rotate(2deg)' },
    durationMs: 70,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 8,
    className: 'animate-cross-shake',
  },
  'wipe-in-left': {
    id: 'wipe-in-left',
    displayName: 'Wipe in (left)',
    intent: 'enter',
    from: { clipPath: 'inset(0 100% 0 0)' },
    to: { clipPath: 'inset(0 0 0 0)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-wipe-in-left',
  },
  'wipe-in-right': {
    id: 'wipe-in-right',
    displayName: 'Wipe in (right)',
    intent: 'enter',
    from: { clipPath: 'inset(0 0 0 100%)' },
    to: { clipPath: 'inset(0 0 0 0)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-wipe-in-right',
  },
  'flicker': {
    id: 'flicker',
    displayName: 'Flicker (neon)',
    intent: 'loop',
    from: { opacity: '1' },
    to: { opacity: '0.4' },
    durationMs: 120,
    easing: 'steps(2, end)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-flicker',
  },
  'card-flip': {
    id: 'card-flip',
    displayName: 'Card flip',
    intent: 'enter',
    from: { transform: 'perspective(800px) rotateY(180deg)' },
    to: { transform: 'perspective(800px) rotateY(0deg)' },
    durationMs: 680,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-card-flip',
  },
  'type-out': {
    id: 'type-out',
    displayName: 'Type out (text)',
    intent: 'enter',
    from: { width: '0' },
    to: { width: '100%' },
    durationMs: 2200,
    easing: 'steps(40, end)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-type-out',
  },
  'fade-in-blur': {
    id: 'fade-in-blur',
    displayName: 'Fade in (blur up)',
    intent: 'enter',
    from: { opacity: '0', filter: 'blur(8px)', transform: 'translateY(12px)' },
    to: { opacity: '1', filter: 'blur(0)', transform: 'translateY(0)' },
    durationMs: 600,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-blur',
  },
  'magnet-pull': {
    id: 'magnet-pull',
    displayName: 'Magnet pull (hover)',
    intent: 'attention',
    from: { transform: 'translate(0, 0)' },
    to: { transform: 'translate(2px, -2px) scale(1.04)' },
    durationMs: 200,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-magnet-pull',
  },
  // ---- Wave 6: 10 more ----
  'slide-out-right': {
    id: 'slide-out-right',
    displayName: 'Slide out (right)',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateX(0)' },
    to: { opacity: '0', transform: 'translateX(24px)' },
    durationMs: 260,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-out-right',
  },
  'slide-out-left': {
    id: 'slide-out-left',
    displayName: 'Slide out (left)',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateX(0)' },
    to: { opacity: '0', transform: 'translateX(-24px)' },
    durationMs: 260,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-out-left',
  },
  'fade-out-down': {
    id: 'fade-out-down',
    displayName: 'Fade out (down)',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateY(0)' },
    to: { opacity: '0', transform: 'translateY(12px)' },
    durationMs: 240,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-out-down',
  },
  'fade-out-up': {
    id: 'fade-out-up',
    displayName: 'Fade out (up)',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateY(0)' },
    to: { opacity: '0', transform: 'translateY(-12px)' },
    durationMs: 240,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-out-up',
  },
  'rubber-band': {
    id: 'rubber-band',
    displayName: 'Rubber band',
    intent: 'attention',
    from: { transform: 'scale(1, 1)' },
    to: { transform: 'scale(1.25, 0.75)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-rubber-band',
  },
  'heartbeat-fast': {
    id: 'heartbeat-fast',
    displayName: 'Heartbeat (fast)',
    intent: 'loop',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.12)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-heartbeat-fast',
  },
  'attention-seek': {
    id: 'attention-seek',
    displayName: 'Attention seek (hand-wave)',
    intent: 'attention',
    from: { transform: 'translateX(0) rotate(0)' },
    to: { transform: 'translateX(8px) rotate(8deg)' },
    durationMs: 120,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-attention-seek',
  },
  'squeeze': {
    id: 'squeeze',
    displayName: 'Squeeze',
    intent: 'attention',
    from: { transform: 'scale(1, 1)' },
    to: { transform: 'scale(0.92, 1.08)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-squeeze',
  },
  'expand-collapse': {
    id: 'expand-collapse',
    displayName: 'Expand-collapse (height)',
    intent: 'enter',
    from: { maxHeight: '0', opacity: '0' },
    to: { maxHeight: '480px', opacity: '1' },
    durationMs: 360,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-expand-collapse',
  },
  'roll-in': {
    id: 'roll-in',
    displayName: 'Roll in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(-100%) rotate(-120deg)' },
    to: { opacity: '1', transform: 'translateX(0) rotate(0deg)' },
    durationMs: 620,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-roll-in',
  },
  // ---- Wave 7: 10 more ----
  'color-shift': {
    id: 'color-shift',
    displayName: 'Color shift',
    intent: 'loop',
    from: { backgroundColor: 'rgb(99,102,241)' },
    to: { backgroundColor: 'rgb(217,70,239)' },
    durationMs: 4200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-color-shift',
  },
  'gradient-shift': {
    id: 'gradient-shift',
    displayName: 'Gradient shift (background)',
    intent: 'loop',
    from: { backgroundPosition: '0% 50%' },
    to: { backgroundPosition: '100% 50%' },
    durationMs: 6000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-gradient-shift',
  },
  'breathe': {
    id: 'breathe',
    displayName: 'Breathe',
    intent: 'loop',
    from: { transform: 'scale(1)', opacity: '0.9' },
    to: { transform: 'scale(1.04)', opacity: '1' },
    durationMs: 3200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-breathe',
  },
  'skew-in': {
    id: 'skew-in',
    displayName: 'Skew in',
    intent: 'enter',
    from: { opacity: '0', transform: 'skewX(-12deg) translateX(-24px)' },
    to: { opacity: '1', transform: 'skewX(0) translateX(0)' },
    durationMs: 460,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-skew-in',
  },
  'elastic-in': {
    id: 'elastic-in',
    displayName: 'Elastic in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.4)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 720,
    easing: 'cubic-bezier(0.68, -0.55, 0.27, 1.55)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-elastic-in',
  },
  'bounce-side': {
    id: 'bounce-side',
    displayName: 'Bounce side-to-side',
    intent: 'attention',
    from: { transform: 'translateX(-6px)' },
    to: { transform: 'translateX(6px)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-bounce-side',
  },
  'text-reveal': {
    id: 'text-reveal',
    displayName: 'Text reveal (clip)',
    intent: 'enter',
    from: { clipPath: 'inset(0 100% 0 0)', opacity: '0' },
    to: { clipPath: 'inset(0 0 0 0)', opacity: '1' },
    durationMs: 780,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-text-reveal',
  },
  'mask-reveal': {
    id: 'mask-reveal',
    displayName: 'Mask reveal (circle)',
    intent: 'enter',
    from: { clipPath: 'circle(0% at 50% 50%)' },
    to: { clipPath: 'circle(100% at 50% 50%)' },
    durationMs: 720,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-mask-reveal',
  },
  'pulse-ring': {
    id: 'pulse-ring',
    displayName: 'Pulse ring',
    intent: 'loop',
    from: { transform: 'scale(0.8)', opacity: '1' },
    to: { transform: 'scale(2)', opacity: '0' },
    durationMs: 1400,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-pulse-ring',
  },
  'shake-vertical': {
    id: 'shake-vertical',
    displayName: 'Shake (vertical)',
    intent: 'attention',
    from: { transform: 'translateY(-4px)' },
    to: { transform: 'translateY(4px)' },
    durationMs: 80,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 6,
    className: 'animate-shake-vertical',
  },
  // ---- Wave 8: 10 more ----
  'slide-up-fade': {
    id: 'slide-up-fade',
    displayName: 'Slide up + fade',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(16px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 420,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-up-fade',
  },
  'slide-down-fade': {
    id: 'slide-down-fade',
    displayName: 'Slide down + fade',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-16px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 420,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-down-fade',
  },
  'swing-in': {
    id: 'swing-in',
    displayName: 'Swing in (3D rotate)',
    intent: 'enter',
    from: { opacity: '0', transform: 'perspective(800px) rotateY(-60deg)', transformOrigin: 'left center' },
    to: { opacity: '1', transform: 'perspective(800px) rotateY(0deg)', transformOrigin: 'left center' },
    durationMs: 580,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-swing-in',
  },
  'swing-out': {
    id: 'swing-out',
    displayName: 'Swing out (3D rotate)',
    intent: 'exit',
    from: { opacity: '1', transform: 'perspective(800px) rotateY(0deg)', transformOrigin: 'left center' },
    to: { opacity: '0', transform: 'perspective(800px) rotateY(-60deg)', transformOrigin: 'left center' },
    durationMs: 380,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-swing-out',
  },
  'pop-in': {
    id: 'pop-in',
    displayName: 'Pop in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.85)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-pop-in',
  },
  'pop-out': {
    id: 'pop-out',
    displayName: 'Pop out',
    intent: 'exit',
    from: { opacity: '1', transform: 'scale(1)' },
    to: { opacity: '0', transform: 'scale(0.85)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-pop-out',
  },
  'float': {
    id: 'float',
    displayName: 'Float (hover idle)',
    intent: 'loop',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-6px)' },
    durationMs: 2400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-float',
  },
  'wave': {
    id: 'wave',
    displayName: 'Wave (undulate)',
    intent: 'attention',
    from: { transform: 'rotate(-14deg)', transformOrigin: '70% 70%' },
    to: { transform: 'rotate(14deg)', transformOrigin: '70% 70%' },
    durationMs: 240,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-wave',
  },
  'zoom-rotate': {
    id: 'zoom-rotate',
    displayName: 'Zoom + rotate',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.4) rotate(-15deg)' },
    to: { opacity: '1', transform: 'scale(1) rotate(0deg)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-zoom-rotate',
  },
  'gentle-pulse': {
    id: 'gentle-pulse',
    displayName: 'Gentle pulse',
    intent: 'loop',
    from: { opacity: '0.85' },
    to: { opacity: '1' },
    durationMs: 2200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-gentle-pulse',
  },
  // ---- Wave 9: 10 more ----
  'slide-fade-up-lg': {
    id: 'slide-fade-up-lg',
    displayName: 'Slide up + fade (large)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(48px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 620,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-fade-up-lg',
  },
  'spring-bounce': {
    id: 'spring-bounce',
    displayName: 'Spring bounce',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.3)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 640,
    easing: 'cubic-bezier(0.5, 1.6, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-spring-bounce',
  },
  'wiggle': {
    id: 'wiggle',
    displayName: 'Wiggle',
    intent: 'attention',
    from: { transform: 'rotate(-6deg)' },
    to: { transform: 'rotate(6deg)' },
    durationMs: 200,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-wiggle',
  },
  'door-open': {
    id: 'door-open',
    displayName: 'Door open (3D)',
    intent: 'enter',
    from: { opacity: '0', transform: 'perspective(800px) rotateY(90deg)', transformOrigin: 'left center' },
    to: { opacity: '1', transform: 'perspective(800px) rotateY(0deg)', transformOrigin: 'left center' },
    durationMs: 720,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-door-open',
  },
  'fold-down': {
    id: 'fold-down',
    displayName: 'Fold down',
    intent: 'exit',
    from: { transform: 'perspective(800px) rotateX(0deg)', transformOrigin: 'top center' },
    to: { transform: 'perspective(800px) rotateX(-90deg)', transformOrigin: 'top center' },
    durationMs: 480,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fold-down',
  },
  'unfold': {
    id: 'unfold',
    displayName: 'Unfold',
    intent: 'enter',
    from: { transform: 'perspective(800px) rotateX(-90deg)', transformOrigin: 'top center' },
    to: { transform: 'perspective(800px) rotateX(0deg)', transformOrigin: 'top center' },
    durationMs: 560,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-unfold',
  },
  'stamp': {
    id: 'stamp',
    displayName: 'Stamp',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(2)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 300,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-stamp',
  },
  'scribble': {
    id: 'scribble',
    displayName: 'Scribble (underline SVG)',
    intent: 'enter',
    from: { strokeDashoffset: '320' },
    to: { strokeDashoffset: '0' },
    durationMs: 900,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 240,
    iterations: 1,
    className: 'animate-scribble',
  },
  'blink': {
    id: 'blink',
    displayName: 'Blink',
    intent: 'loop',
    from: { opacity: '1' },
    to: { opacity: '0' },
    durationMs: 420,
    easing: 'steps(2, end)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-blink',
  },
  'dash-stroke': {
    id: 'dash-stroke',
    displayName: 'Marching ants (border)',
    intent: 'loop',
    from: { backgroundPosition: '0 0, 0 0, 0 100%, 100% 0' },
    to: { backgroundPosition: '12px 0, 0 12px, -12px 100%, 100% -12px' },
    durationMs: 600,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-dash-stroke',
  },
  // ---- Wave 10: 10 more → reaches 100-preset milestone ----
  'lift': {
    id: 'lift',
    displayName: 'Lift (hover)',
    intent: 'attention',
    from: { transform: 'translateY(0)', boxShadow: '0 1px 2px rgba(0,0,0,0.05)' },
    to: { transform: 'translateY(-4px)', boxShadow: '0 12px 24px rgba(0,0,0,0.12)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-lift',
  },
  'settle': {
    id: 'settle',
    displayName: 'Settle (drop & rest)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-20px) scale(1.05)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.5, 1.3, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-settle',
  },
  'wiggle-bounce': {
    id: 'wiggle-bounce',
    displayName: 'Wiggle + bounce',
    intent: 'attention',
    from: { transform: 'rotate(-8deg) translateY(0)' },
    to: { transform: 'rotate(8deg) translateY(-6px)' },
    durationMs: 200,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-wiggle-bounce',
  },
  'shake-once': {
    id: 'shake-once',
    displayName: 'Shake once',
    intent: 'attention',
    from: { transform: 'translateX(-8px)' },
    to: { transform: 'translateX(0)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.36, 0.07, 0.19, 0.97)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-shake-once',
  },
  'text-pop': {
    id: 'text-pop',
    displayName: 'Text pop (per-char)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px) scale(0.85)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 40,
    iterations: 1,
    className: 'animate-text-pop',
  },
  'cascade-fade': {
    id: 'cascade-fade',
    displayName: 'Cascade fade (list children)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(12px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 260,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 80,
    iterations: 1,
    className: 'animate-cascade-fade',
  },
  'fall-in': {
    id: 'fall-in',
    displayName: 'Fall in (gravity)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-80px) rotate(-8deg)' },
    to: { opacity: '1', transform: 'translateY(0) rotate(0deg)' },
    durationMs: 720,
    easing: 'cubic-bezier(0.5, 1.3, 0.4, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fall-in',
  },
  'snap-in': {
    id: 'snap-in',
    displayName: 'Snap in (crisp pop)',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.5)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 160,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-snap-in',
  },
  'dissolve': {
    id: 'dissolve',
    displayName: 'Dissolve (filter blur out)',
    intent: 'exit',
    from: { opacity: '1', filter: 'blur(0)' },
    to: { opacity: '0', filter: 'blur(8px)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-dissolve',
  },
  'cube-rotate': {
    id: 'cube-rotate',
    displayName: 'Cube rotate (3D)',
    intent: 'loop',
    from: { transform: 'perspective(600px) rotateX(0deg) rotateY(0deg)' },
    to: { transform: 'perspective(600px) rotateX(360deg) rotateY(360deg)' },
    durationMs: 8000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-cube-rotate',
  },
  // ---- Wave 11: 10 more (stretch beyond 100-cap) ----
  'typewriter': {
    id: 'typewriter',
    displayName: 'Typewriter (steps)',
    intent: 'enter',
    from: { width: '0', borderRight: '2px solid currentColor' },
    to: { width: '100%', borderRight: '2px solid transparent' },
    durationMs: 2400,
    easing: 'steps(28, end)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-typewriter',
  },
  'ring-pulse': {
    id: 'ring-pulse',
    displayName: 'Ring pulse (notification)',
    intent: 'loop',
    from: { boxShadow: '0 0 0 0 currentColor' },
    to: { boxShadow: '0 0 0 12px transparent' },
    durationMs: 1400,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-ring-pulse',
  },
  'tilt': {
    id: 'tilt',
    displayName: 'Tilt (hover)',
    intent: 'attention',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(-4deg) scale(1.02)' },
    durationMs: 240,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-tilt',
  },
  'slide-rotate-in': {
    id: 'slide-rotate-in',
    displayName: 'Slide + rotate in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(-40px) rotate(-8deg)' },
    to: { opacity: '1', transform: 'translateX(0) rotate(0deg)' },
    durationMs: 560,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-rotate-in',
  },
  'zoom-fade-in': {
    id: 'zoom-fade-in',
    displayName: 'Zoom + fade in',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(1.06)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-zoom-fade-in',
  },
  'nudge-right': {
    id: 'nudge-right',
    displayName: 'Nudge right (CTA arrow)',
    intent: 'attention',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(4px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-nudge-right',
  },
  'nudge-left': {
    id: 'nudge-left',
    displayName: 'Nudge left (back arrow)',
    intent: 'attention',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(-4px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-nudge-left',
  },
  'drop-bounce': {
    id: 'drop-bounce',
    displayName: 'Drop bounce',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-40px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 720,
    easing: 'cubic-bezier(0.5, 1.8, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-drop-bounce',
  },
  'peek': {
    id: 'peek',
    displayName: 'Peek (slide-up partial)',
    intent: 'attention',
    from: { transform: 'translateY(100%)' },
    to: { transform: 'translateY(75%)' },
    durationMs: 480,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-peek',
  },
  'depth-shift': {
    id: 'depth-shift',
    displayName: 'Depth shift (parallax tile)',
    intent: 'attention',
    from: { transform: 'translateZ(0) translateY(0)' },
    to: { transform: 'translateZ(20px) translateY(-4px)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-depth-shift',
  },
  // ---- Wave 12: 10 more (stretch) ----
  'ripple-out': {
    id: 'ripple-out',
    displayName: 'Ripple out',
    intent: 'attention',
    from: { transform: 'scale(0.8)', opacity: '0.8' },
    to: { transform: 'scale(2.4)', opacity: '0' },
    durationMs: 1100,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-ripple-out',
  },
  'door-close': {
    id: 'door-close',
    displayName: 'Door close (3D)',
    intent: 'exit',
    from: { opacity: '1', transform: 'perspective(800px) rotateY(0deg)', transformOrigin: 'left center' },
    to: { opacity: '0', transform: 'perspective(800px) rotateY(90deg)', transformOrigin: 'left center' },
    durationMs: 460,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-door-close',
  },
  'icon-spin-fast': {
    id: 'icon-spin-fast',
    displayName: 'Icon spin (very fast)',
    intent: 'loop',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
    durationMs: 500,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-icon-spin-fast',
  },
  'blob-morph': {
    id: 'blob-morph',
    displayName: 'Blob morph',
    intent: 'loop',
    from: { borderRadius: '60% 40% 30% 70% / 60% 30% 70% 40%' },
    to: { borderRadius: '30% 60% 70% 40% / 50% 60% 30% 60%' },
    durationMs: 8000,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-blob-morph',
  },
  'shimmer-line': {
    id: 'shimmer-line',
    displayName: 'Shimmer line (skeleton)',
    intent: 'loop',
    from: { backgroundPosition: '-300% 0' },
    to: { backgroundPosition: '300% 0' },
    durationMs: 1800,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-shimmer-line',
  },
  'text-glow': {
    id: 'text-glow',
    displayName: 'Text glow',
    intent: 'loop',
    from: { textShadow: '0 0 4px currentColor' },
    to: { textShadow: '0 0 24px currentColor' },
    durationMs: 1800,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-text-glow',
  },
  'heartbeat-slow': {
    id: 'heartbeat-slow',
    displayName: 'Heartbeat (slow)',
    intent: 'loop',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.04)' },
    durationMs: 1600,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-heartbeat-slow',
  },
  'fade-up-mini': {
    id: 'fade-up-mini',
    displayName: 'Fade up (mini)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(4px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 200,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-up-mini',
  },
  'peek-up': {
    id: 'peek-up',
    displayName: 'Peek up (toast in)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(120%)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-peek-up',
  },
  'radar': {
    id: 'radar',
    displayName: 'Radar sweep',
    intent: 'loop',
    from: { transform: 'rotate(0deg)', transformOrigin: 'center' },
    to: { transform: 'rotate(360deg)', transformOrigin: 'center' },
    durationMs: 3200,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-radar',
  },
  // ---- Wave 13: 10 more (stretch) ----
  'swing-up': {
    id: 'swing-up',
    displayName: 'Swing up (pendulum)',
    intent: 'enter',
    from: { opacity: '0', transform: 'rotate(-12deg) translateY(20px)', transformOrigin: 'top center' },
    to: { opacity: '1', transform: 'rotate(0deg) translateY(0)', transformOrigin: 'top center' },
    durationMs: 580,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-swing-up',
  },
  'drift-left': {
    id: 'drift-left',
    displayName: 'Drift left (idle)',
    intent: 'loop',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(-6px)' },
    durationMs: 3000,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-drift-left',
  },
  'drift-right': {
    id: 'drift-right',
    displayName: 'Drift right (idle)',
    intent: 'loop',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(6px)' },
    durationMs: 3000,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-drift-right',
  },
  'text-wave': {
    id: 'text-wave',
    displayName: 'Text wave (per-letter)',
    intent: 'loop',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-6px)' },
    durationMs: 1200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 80,
    iterations: 'infinite',
    className: 'animate-text-wave',
  },
  'glow-border': {
    id: 'glow-border',
    displayName: 'Glow border (focus)',
    intent: 'loop',
    from: { boxShadow: '0 0 0 0 currentColor' },
    to: { boxShadow: '0 0 0 4px currentColor' },
    durationMs: 1600,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-glow-border',
  },
  'wave-vertical': {
    id: 'wave-vertical',
    displayName: 'Wave vertical',
    intent: 'loop',
    from: { transform: 'translateY(-3px)' },
    to: { transform: 'translateY(3px)' },
    durationMs: 1800,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-wave-vertical',
  },
  'blink-once': {
    id: 'blink-once',
    displayName: 'Blink once',
    intent: 'attention',
    from: { opacity: '1' },
    to: { opacity: '0.3' },
    durationMs: 280,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-blink-once',
  },
  'soft-bounce': {
    id: 'soft-bounce',
    displayName: 'Soft bounce',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px) scale(0.98)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 440,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-soft-bounce',
  },
  'flag-wave': {
    id: 'flag-wave',
    displayName: 'Flag wave',
    intent: 'loop',
    from: { transform: 'skewY(-3deg)' },
    to: { transform: 'skewY(3deg)' },
    durationMs: 2400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-flag-wave',
  },
  'confetti-burst': {
    id: 'confetti-burst',
    displayName: 'Confetti burst',
    intent: 'attention',
    from: { opacity: '1', transform: 'scale(0.3) rotate(0deg)' },
    to: { opacity: '0', transform: 'scale(1.4) rotate(180deg) translateY(-40px)' },
    durationMs: 900,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-confetti-burst',
  },
  // ---- Wave 14: 10 more (stretch) ----
  'orbit': {
    id: 'orbit',
    displayName: 'Orbit (circle around)',
    intent: 'loop',
    from: { transform: 'rotate(0deg) translateX(20px) rotate(0deg)' },
    to: { transform: 'rotate(360deg) translateX(20px) rotate(-360deg)' },
    durationMs: 4000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-orbit',
  },
  'depth-pulse': {
    id: 'depth-pulse',
    displayName: 'Depth pulse (z scale)',
    intent: 'loop',
    from: { transform: 'perspective(800px) translateZ(0)' },
    to: { transform: 'perspective(800px) translateZ(20px)' },
    durationMs: 2200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-depth-pulse',
  },
  'fade-rise': {
    id: 'fade-rise',
    displayName: 'Fade rise (parallax in)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(60px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 880,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-rise',
  },
  'slide-shift': {
    id: 'slide-shift',
    displayName: 'Slide shift (carousel)',
    intent: 'enter',
    from: { transform: 'translateX(100%)' },
    to: { transform: 'translateX(0)' },
    durationMs: 480,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-shift',
  },
  'text-shimmer': {
    id: 'text-shimmer',
    displayName: 'Text shimmer (gradient sweep)',
    intent: 'loop',
    from: { backgroundPosition: '-200% center' },
    to: { backgroundPosition: '200% center' },
    durationMs: 2800,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-text-shimmer',
  },
  'flash': {
    id: 'flash',
    displayName: 'Flash',
    intent: 'attention',
    from: { opacity: '1' },
    to: { opacity: '0' },
    durationMs: 80,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 6,
    className: 'animate-flash',
  },
  'fade-cycle': {
    id: 'fade-cycle',
    displayName: 'Fade cycle (loop fade)',
    intent: 'loop',
    from: { opacity: '0.5' },
    to: { opacity: '1' },
    durationMs: 2400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-fade-cycle',
  },
  'zoom-decay': {
    id: 'zoom-decay',
    displayName: 'Zoom decay (settle in)',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(1.5)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 520,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-zoom-decay',
  },
  'arc-in': {
    id: 'arc-in',
    displayName: 'Arc in (curved path)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translate(40px, -20px) rotate(-20deg)' },
    to: { opacity: '1', transform: 'translate(0, 0) rotate(0deg)' },
    durationMs: 640,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-arc-in',
  },
  'emerge': {
    id: 'emerge',
    displayName: 'Emerge (clip-path)',
    intent: 'enter',
    from: { clipPath: 'polygon(0 100%, 100% 100%, 100% 100%, 0 100%)', opacity: '0' },
    to: { clipPath: 'polygon(0 0, 100% 0, 100% 100%, 0 100%)', opacity: '1' },
    durationMs: 720,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-emerge',
  },
  // ---- Wave 15: 10 more (reaches 150-preset milestone) ----
  'ping-once': {
    id: 'ping-once',
    displayName: 'Ping once',
    intent: 'attention',
    from: { transform: 'scale(1)', opacity: '1' },
    to: { transform: 'scale(2.4)', opacity: '0' },
    durationMs: 720,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-ping-once',
  },
  'wobble-x': {
    id: 'wobble-x',
    displayName: 'Wobble (x-axis)',
    intent: 'attention',
    from: { transform: 'translateX(-8px)' },
    to: { transform: 'translateX(8px)' },
    durationMs: 100,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 5,
    className: 'animate-wobble-x',
  },
  'wobble-y': {
    id: 'wobble-y',
    displayName: 'Wobble (y-axis)',
    intent: 'attention',
    from: { transform: 'translateY(-6px)' },
    to: { transform: 'translateY(6px)' },
    durationMs: 100,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 5,
    className: 'animate-wobble-y',
  },
  'lean-left': {
    id: 'lean-left',
    displayName: 'Lean left',
    intent: 'attention',
    from: { transform: 'rotate(0)' },
    to: { transform: 'rotate(-6deg)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-lean-left',
  },
  'lean-right': {
    id: 'lean-right',
    displayName: 'Lean right',
    intent: 'attention',
    from: { transform: 'rotate(0)' },
    to: { transform: 'rotate(6deg)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-lean-right',
  },
  'pop-up': {
    id: 'pop-up',
    displayName: 'Pop up (tooltip in)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px) scale(0.95)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-pop-up',
  },
  'burst': {
    id: 'burst',
    displayName: 'Burst (firework)',
    intent: 'attention',
    from: { transform: 'scale(0)', opacity: '1' },
    to: { transform: 'scale(2.2)', opacity: '0' },
    durationMs: 600,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-burst',
  },
  'heart-fill': {
    id: 'heart-fill',
    displayName: 'Heart fill (like)',
    intent: 'attention',
    from: { transform: 'scale(0.7)', opacity: '0.4' },
    to: { transform: 'scale(1.2)', opacity: '1' },
    durationMs: 360,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-heart-fill',
  },
  'wave-svg': {
    id: 'wave-svg',
    displayName: 'Wave (SVG dash)',
    intent: 'loop',
    from: { strokeDashoffset: '0' },
    to: { strokeDashoffset: '-200' },
    durationMs: 3000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-wave-svg',
  },
  'orbit-fast': {
    id: 'orbit-fast',
    displayName: 'Orbit (fast)',
    intent: 'loop',
    from: { transform: 'rotate(0deg) translateX(12px) rotate(0deg)' },
    to: { transform: 'rotate(360deg) translateX(12px) rotate(-360deg)' },
    durationMs: 1600,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-orbit-fast',
  },
  // ---- Wave 16: 10 more (stretch) ----
  'drop-shadow-rise': {
    id: 'drop-shadow-rise',
    displayName: 'Drop shadow rise (lift)',
    intent: 'attention',
    from: { transform: 'translateY(0)', filter: 'drop-shadow(0 2px 4px rgba(0,0,0,0.1))' },
    to: { transform: 'translateY(-3px)', filter: 'drop-shadow(0 12px 18px rgba(0,0,0,0.2))' },
    durationMs: 240,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-drop-shadow-rise',
  },
  'nudge-down': {
    id: 'nudge-down',
    displayName: 'Nudge down',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(4px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-nudge-down',
  },
  'nudge-up': {
    id: 'nudge-up',
    displayName: 'Nudge up',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-4px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-nudge-up',
  },
  'squash': {
    id: 'squash',
    displayName: 'Squash',
    intent: 'attention',
    from: { transform: 'scaleY(1)' },
    to: { transform: 'scaleY(0.85)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-squash',
  },
  'stretch': {
    id: 'stretch',
    displayName: 'Stretch',
    intent: 'attention',
    from: { transform: 'scaleY(1)' },
    to: { transform: 'scaleY(1.15)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-stretch',
  },
  'tick-second': {
    id: 'tick-second',
    displayName: 'Tick (clock second)',
    intent: 'loop',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(360deg)' },
    durationMs: 60000,
    easing: 'steps(60, end)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-tick-second',
  },
  'inflate': {
    id: 'inflate',
    displayName: 'Inflate',
    intent: 'enter',
    from: { transform: 'scale(0)' },
    to: { transform: 'scale(1)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-inflate',
  },
  'deflate': {
    id: 'deflate',
    displayName: 'Deflate',
    intent: 'exit',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(0)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-deflate',
  },
  'light-sweep': {
    id: 'light-sweep',
    displayName: 'Light sweep (gradient)',
    intent: 'loop',
    from: { backgroundPosition: '-200% 0' },
    to: { backgroundPosition: '300% 0' },
    durationMs: 3200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-light-sweep',
  },
  'slow-pan': {
    id: 'slow-pan',
    displayName: 'Slow pan (background)',
    intent: 'loop',
    from: { backgroundPosition: '0% 50%' },
    to: { backgroundPosition: '100% 50%' },
    durationMs: 20000,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-slow-pan',
  },
  // ---- Wave 17: 10 more (stretch) ----
  'fade-in-fast': {
    id: 'fade-in-fast',
    displayName: 'Fade in (fast)',
    intent: 'enter',
    from: { opacity: '0' },
    to: { opacity: '1' },
    durationMs: 140,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-fast',
  },
  'slide-fade-down-lg': {
    id: 'slide-fade-down-lg',
    displayName: 'Slide down + fade (large)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-48px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 620,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-fade-down-lg',
  },
  'rebound': {
    id: 'rebound',
    displayName: 'Rebound',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-12px)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.5, 1.6, 0.6, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-rebound',
  },
  'throb': {
    id: 'throb',
    displayName: 'Throb (scale loop)',
    intent: 'loop',
    from: { transform: 'scale(0.96)' },
    to: { transform: 'scale(1.04)' },
    durationMs: 1100,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-throb',
  },
  'swing-pendulum': {
    id: 'swing-pendulum',
    displayName: 'Swing pendulum',
    intent: 'loop',
    from: { transform: 'rotate(-8deg)', transformOrigin: 'top center' },
    to: { transform: 'rotate(8deg)', transformOrigin: 'top center' },
    durationMs: 1800,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-swing-pendulum',
  },
  'drop-fade': {
    id: 'drop-fade',
    displayName: 'Drop fade out',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateY(0)' },
    to: { opacity: '0', transform: 'translateY(20px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-drop-fade',
  },
  'text-wave-lg': {
    id: 'text-wave-lg',
    displayName: 'Text wave (big amplitude)',
    intent: 'loop',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-12px)' },
    durationMs: 1400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 120,
    iterations: 'infinite',
    className: 'animate-text-wave-lg',
  },
  'press-down': {
    id: 'press-down',
    displayName: 'Press down (button)',
    intent: 'attention',
    from: { transform: 'translateY(0)', boxShadow: '0 4px 6px rgba(0,0,0,.1)' },
    to: { transform: 'translateY(2px)', boxShadow: '0 1px 2px rgba(0,0,0,.1)' },
    durationMs: 100,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-press-down',
  },
  'raise-up': {
    id: 'raise-up',
    displayName: 'Raise up (hover lift)',
    intent: 'attention',
    from: { transform: 'translateY(0)', boxShadow: '0 1px 2px rgba(0,0,0,.06)' },
    to: { transform: 'translateY(-6px)', boxShadow: '0 16px 24px rgba(0,0,0,.18)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-raise-up',
  },
  'spotlight': {
    id: 'spotlight',
    displayName: 'Spotlight (radial gradient sweep)',
    intent: 'loop',
    from: { backgroundPosition: '0% 0%' },
    to: { backgroundPosition: '100% 100%' },
    durationMs: 4200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-spotlight',
  },
  // ---- Wave 18: 10 more (stretch) ----
  'pop-down': {
    id: 'pop-down',
    displayName: 'Pop down (dropdown enter)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-6px) scale(0.96)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 180,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-pop-down',
  },
  'wiggle-vertical': {
    id: 'wiggle-vertical',
    displayName: 'Wiggle (vertical)',
    intent: 'attention',
    from: { transform: 'translateY(-4px)' },
    to: { transform: 'translateY(4px)' },
    durationMs: 100,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-wiggle-vertical',
  },
  'throb-text': {
    id: 'throb-text',
    displayName: 'Throb text (letter-spacing pulse)',
    intent: 'loop',
    from: { letterSpacing: '0.02em' },
    to: { letterSpacing: '0.16em' },
    durationMs: 2200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-throb-text',
  },
  'unfurl': {
    id: 'unfurl',
    displayName: 'Unfurl (scaleX from 0)',
    intent: 'enter',
    from: { transform: 'scaleX(0)', transformOrigin: 'left center' },
    to: { transform: 'scaleX(1)', transformOrigin: 'left center' },
    durationMs: 460,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-unfurl',
  },
  'button-press': {
    id: 'button-press',
    displayName: 'Button press (active)',
    intent: 'attention',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(0.95)' },
    durationMs: 80,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-button-press',
  },
  'quick-flash': {
    id: 'quick-flash',
    displayName: 'Quick flash (single)',
    intent: 'attention',
    from: { backgroundColor: 'currentColor', opacity: '0.5' },
    to: { backgroundColor: 'transparent', opacity: '1' },
    durationMs: 220,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-quick-flash',
  },
  'opacity-cycle': {
    id: 'opacity-cycle',
    displayName: 'Opacity cycle (loop)',
    intent: 'loop',
    from: { opacity: '0.3' },
    to: { opacity: '1' },
    durationMs: 1600,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-opacity-cycle',
  },
  'slide-bounce-in': {
    id: 'slide-bounce-in',
    displayName: 'Slide bounce in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateX(-60px)' },
    to: { opacity: '1', transform: 'translateX(0)' },
    durationMs: 620,
    easing: 'cubic-bezier(0.5, 1.6, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-slide-bounce-in',
  },
  'snake-line': {
    id: 'snake-line',
    displayName: 'Snake line (border march)',
    intent: 'loop',
    from: { backgroundPosition: '0 0' },
    to: { backgroundPosition: '40px 0' },
    durationMs: 1200,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-snake-line',
  },
  'ping-double': {
    id: 'ping-double',
    displayName: 'Ping (double radar)',
    intent: 'loop',
    from: { transform: 'scale(1)', opacity: '0.6' },
    to: { transform: 'scale(2)', opacity: '0' },
    durationMs: 1000,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 200,
    iterations: 'infinite',
    className: 'animate-ping-double',
  },
  // ---- Wave 19: 10 more (stretch) ----
  'wave-text-color': {
    id: 'wave-text-color',
    displayName: 'Wave text color',
    intent: 'loop',
    from: { color: 'currentColor', filter: 'hue-rotate(0deg)' },
    to: { color: 'currentColor', filter: 'hue-rotate(360deg)' },
    durationMs: 4200,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-wave-text-color',
  },
  'cursor-blink': {
    id: 'cursor-blink',
    displayName: 'Cursor blink (text caret)',
    intent: 'loop',
    from: { borderRightColor: 'currentColor' },
    to: { borderRightColor: 'transparent' },
    durationMs: 800,
    easing: 'steps(2, end)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-cursor-blink',
  },
  'dot-loader': {
    id: 'dot-loader',
    displayName: 'Dot loader (3 dots bounce)',
    intent: 'loop',
    from: { transform: 'translateY(0)', opacity: '0.3' },
    to: { transform: 'translateY(-6px)', opacity: '1' },
    durationMs: 600,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 100,
    iterations: 'infinite',
    className: 'animate-dot-loader',
  },
  'accordion-down': {
    id: 'accordion-down',
    displayName: 'Accordion down (expand)',
    intent: 'enter',
    from: { maxHeight: '0', opacity: '0' },
    to: { maxHeight: '320px', opacity: '1' },
    durationMs: 280,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-accordion-down',
  },
  'accordion-up': {
    id: 'accordion-up',
    displayName: 'Accordion up (collapse)',
    intent: 'exit',
    from: { maxHeight: '320px', opacity: '1' },
    to: { maxHeight: '0', opacity: '0' },
    durationMs: 220,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-accordion-up',
  },
  'tooltip-in': {
    id: 'tooltip-in',
    displayName: 'Tooltip in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(4px) scale(0.95)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 120,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-tooltip-in',
  },
  'tooltip-out': {
    id: 'tooltip-out',
    displayName: 'Tooltip out',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateY(0) scale(1)' },
    to: { opacity: '0', transform: 'translateY(4px) scale(0.95)' },
    durationMs: 100,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-tooltip-out',
  },
  'drift-up': {
    id: 'drift-up',
    displayName: 'Drift up (idle)',
    intent: 'loop',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-6px)' },
    durationMs: 3200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-drift-up',
  },
  'drift-down': {
    id: 'drift-down',
    displayName: 'Drift down (idle)',
    intent: 'loop',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(6px)' },
    durationMs: 3200,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-drift-down',
  },
  'swing-bounce': {
    id: 'swing-bounce',
    displayName: 'Swing + bounce (combo)',
    intent: 'attention',
    from: { transform: 'rotate(-8deg) translateY(0)' },
    to: { transform: 'rotate(8deg) translateY(-8px)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-swing-bounce',
  },
  // ---- Wave 20: 10 more (reaches 200-preset, 2× year-1 cap) ----
  'open-up': {
    id: 'open-up',
    displayName: 'Open up (drawer enter)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(40px) scale(0.98)' },
    to: { opacity: '1', transform: 'translateY(0) scale(1)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-open-up',
  },
  'close-down': {
    id: 'close-down',
    displayName: 'Close down (drawer exit)',
    intent: 'exit',
    from: { opacity: '1', transform: 'translateY(0) scale(1)' },
    to: { opacity: '0', transform: 'translateY(40px) scale(0.98)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.4, 0, 1, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-close-down',
  },
  'cascade-stagger': {
    id: 'cascade-stagger',
    displayName: 'Cascade stagger (list)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(12px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 60,
    iterations: 1,
    className: 'animate-cascade-stagger',
  },
  'half-rotate': {
    id: 'half-rotate',
    displayName: 'Half rotate',
    intent: 'attention',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(180deg)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-half-rotate',
  },
  'bounce-in-mini': {
    id: 'bounce-in-mini',
    displayName: 'Bounce in (mini)',
    intent: 'enter',
    from: { opacity: '0', transform: 'scale(0.85)' },
    to: { opacity: '1', transform: 'scale(1)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.5, 1.6, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-bounce-in-mini',
  },
  'flip-card': {
    id: 'flip-card',
    displayName: 'Flip card (hover)',
    intent: 'attention',
    from: { transform: 'perspective(800px) rotateY(0deg)' },
    to: { transform: 'perspective(800px) rotateY(180deg)' },
    durationMs: 560,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-flip-card',
  },
  'lift-fade': {
    id: 'lift-fade',
    displayName: 'Lift + fade in',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(20px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 380,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-lift-fade',
  },
  'fade-rise-fast': {
    id: 'fade-rise-fast',
    displayName: 'Fade rise (fast)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(8px)' },
    to: { opacity: '1', transform: 'translateY(0)' },
    durationMs: 160,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-rise-fast',
  },
  'sparkle': {
    id: 'sparkle',
    displayName: 'Sparkle (twinkle)',
    intent: 'loop',
    from: { opacity: '0.2', transform: 'scale(0.6) rotate(0deg)' },
    to: { opacity: '1', transform: 'scale(1.4) rotate(360deg)' },
    durationMs: 1400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-sparkle',
  },
  'glitter-shake': {
    id: 'glitter-shake',
    displayName: 'Glitter shake (combo)',
    intent: 'attention',
    from: { transform: 'rotate(-3deg) scale(1)', filter: 'brightness(1)' },
    to: { transform: 'rotate(3deg) scale(1.08)', filter: 'brightness(1.3)' },
    durationMs: 140,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 5,
    className: 'animate-glitter-shake',
  },
  // ---- Wave 21: 10 more (stretch) ----
  'roll-bounce': {
    id: 'roll-bounce',
    displayName: 'Roll bounce (combo)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-40px) rotate(-90deg)' },
    to: { opacity: '1', transform: 'translateY(0) rotate(0deg)' },
    durationMs: 720,
    easing: 'cubic-bezier(0.5, 1.5, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-roll-bounce',
  },
  'dim-flash': {
    id: 'dim-flash',
    displayName: 'Dim flash (subtle)',
    intent: 'attention',
    from: { opacity: '1' },
    to: { opacity: '0.7' },
    durationMs: 320,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-dim-flash',
  },
  'depth-tilt': {
    id: 'depth-tilt',
    displayName: 'Depth tilt (hover)',
    intent: 'attention',
    from: { transform: 'perspective(800px) rotateX(0deg) rotateY(0deg)' },
    to: { transform: 'perspective(800px) rotateX(-3deg) rotateY(3deg) translateZ(6px)' },
    durationMs: 280,
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-depth-tilt',
  },
  'surge': {
    id: 'surge',
    displayName: 'Surge (scale-spike)',
    intent: 'attention',
    from: { transform: 'scale(1)', filter: 'brightness(1)' },
    to: { transform: 'scale(1.15)', filter: 'brightness(1.2)' },
    durationMs: 240,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-surge',
  },
  'depress-up': {
    id: 'depress-up',
    displayName: 'Depress + spring up',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-4px)' },
    durationMs: 320,
    easing: 'cubic-bezier(0.5, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-depress-up',
  },
  'pendulum': {
    id: 'pendulum',
    displayName: 'Pendulum (loop swing)',
    intent: 'loop',
    from: { transform: 'rotate(-12deg)', transformOrigin: 'top center' },
    to: { transform: 'rotate(12deg)', transformOrigin: 'top center' },
    durationMs: 2400,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-pendulum',
  },
  'heartbeat-once': {
    id: 'heartbeat-once',
    displayName: 'Heartbeat (one beat)',
    intent: 'attention',
    from: { transform: 'scale(1)' },
    to: { transform: 'scale(1.15)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-heartbeat-once',
  },
  'depth-zoom': {
    id: 'depth-zoom',
    displayName: 'Depth zoom (background)',
    intent: 'loop',
    from: { backgroundSize: '100% 100%' },
    to: { backgroundSize: '110% 110%' },
    durationMs: 8000,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-depth-zoom',
  },
  'nudge-rotate': {
    id: 'nudge-rotate',
    displayName: 'Nudge + rotate (hover icon)',
    intent: 'attention',
    from: { transform: 'translateX(0) rotate(0)' },
    to: { transform: 'translateX(3px) rotate(8deg)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-nudge-rotate',
  },
  'wipe-down': {
    id: 'wipe-down',
    displayName: 'Wipe down (reveal top-to-bottom)',
    intent: 'enter',
    from: { clipPath: 'inset(0 0 100% 0)' },
    to: { clipPath: 'inset(0 0 0 0)' },
    durationMs: 480,
    easing: 'cubic-bezier(0.65, 0, 0.35, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-wipe-down',
  },
  'shimmer-rotate': {
    id: 'shimmer-rotate',
    displayName: 'Shimmer + rotate (loading badge)',
    intent: 'loop',
    from: { transform: 'rotate(0deg)', opacity: '0.6' },
    to: { transform: 'rotate(360deg)', opacity: '1' },
    durationMs: 1800,
    easing: 'linear',
    delayMs: 0,
    iterations: 'infinite',
    className: 'animate-shimmer-rotate',
  },
  'card-tilt': {
    id: 'card-tilt',
    displayName: 'Card tilt (3D hover)',
    intent: 'attention',
    from: { transform: 'perspective(800px) rotateX(0) rotateY(0)' },
    to: { transform: 'perspective(800px) rotateX(6deg) rotateY(-6deg)' },
    durationMs: 260,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-card-tilt',
  },
  'peek-down': {
    id: 'peek-down',
    displayName: 'Peek down (dropdown reveal)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateY(-8px) scaleY(0.95)' },
    to: { opacity: '1', transform: 'translateY(0) scaleY(1)' },
    durationMs: 220,
    easing: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-peek-down',
  },
  'fade-in-blur-fast': {
    id: 'fade-in-blur-fast',
    displayName: 'Fade-in + blur (fast)',
    intent: 'enter',
    from: { opacity: '0', filter: 'blur(8px)' },
    to: { opacity: '1', filter: 'blur(0)' },
    durationMs: 200,
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-fade-in-blur-fast',
  },
  'text-scramble': {
    id: 'text-scramble',
    displayName: 'Text scramble (decoder reveal)',
    intent: 'enter',
    from: { opacity: '0.4', filter: 'blur(2px)', letterSpacing: '0.3em' },
    to: { opacity: '1', filter: 'blur(0)', letterSpacing: 'normal' },
    durationMs: 620,
    easing: 'cubic-bezier(0.4, 0, 0.2, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-text-scramble',
  },
  'opacity-flash': {
    id: 'opacity-flash',
    displayName: 'Opacity flash (notification ping)',
    intent: 'attention',
    from: { opacity: '0.3' },
    to: { opacity: '1' },
    durationMs: 240,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 3,
    className: 'animate-opacity-flash',
  },
  'soft-shake': {
    id: 'soft-shake',
    displayName: 'Soft shake (gentle error)',
    intent: 'attention',
    from: { transform: 'translateX(0)' },
    to: { transform: 'translateX(-2px)' },
    durationMs: 90,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 4,
    className: 'animate-soft-shake',
  },
  'mini-bounce': {
    id: 'mini-bounce',
    displayName: 'Mini bounce (badge pop)',
    intent: 'attention',
    from: { transform: 'translateY(0)' },
    to: { transform: 'translateY(-4px)' },
    durationMs: 200,
    easing: 'cubic-bezier(0.34, 1.78, 0.64, 1)',
    delayMs: 0,
    iterations: 2,
    className: 'animate-mini-bounce',
  },
  'depth-pop': {
    id: 'depth-pop',
    displayName: 'Depth pop (Z-axis surface lift)',
    intent: 'enter',
    from: { opacity: '0', transform: 'translateZ(-40px) scale(0.92)' },
    to: { opacity: '1', transform: 'translateZ(0) scale(1)' },
    durationMs: 360,
    easing: 'cubic-bezier(0.22, 1, 0.36, 1)',
    delayMs: 0,
    iterations: 1,
    className: 'animate-depth-pop',
  },
  'quick-shake': {
    id: 'quick-shake',
    displayName: 'Quick shake (rapid wiggle)',
    intent: 'attention',
    from: { transform: 'rotate(0deg)' },
    to: { transform: 'rotate(4deg)' },
    durationMs: 70,
    easing: 'cubic-bezier(0.4, 0, 0.6, 1)',
    delayMs: 0,
    iterations: 6,
    className: 'animate-quick-shake',
  },
}


export function getMotionPreset(id: string): MotionPreset | null {
  return MOTION_PRESET_CATALOG[id] ?? null
}


export function listMotionPresets(intent?: MotionIntent): MotionPreset[] {
  const all = Object.values(MOTION_PRESET_CATALOG)
  return intent ? all.filter((p) => p.intent === intent) : all
}
