export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center gap-4 p-8">
      <h1 className="text-5xl font-bold tracking-tight">Hello.</h1>
      <p className="text-muted-foreground">Generated by b-dash.</p>
    </main>
  )
}
