/**
 * GET /api/sections/thumbnail/<id>
 *
 * Returns a thumbnail image for one section.
 *
 * Sprint 1a (now): SVG card with section accent + category icon + name
 *   — visually scannable in the palette, no Playwright needed.
 * Sprint 1b (next commit): real PNG screenshot generated by Playwright
 *   against a live running generated app. Cached PNGs at
 *   apps/studio/public/thumbnails/<id>.png — if present they win.
 *
 * Cache header set to 1 day for SVGs (regenerate cheap if catalog adds
 * sections). PNG cache served by Next's static-file middleware.
 */
import { NextResponse } from 'next/server'
import { readFile, stat } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parse as parseYaml } from 'yaml'

const PROJECT_ROOT = resolve(process.cwd(), '..', '..')
const SECTIONS_DIR = resolve(PROJECT_ROOT, 'sections')
const PUBLIC_THUMBS = resolve(process.cwd(), 'public', 'thumbnails')

type Params = { params: Promise<{ id: string }> }

/** Loose lookup: scan sections/<category>/<id>/section.yaml until match. */
async function findSection(id: string): Promise<{ id: string; displayName: string; description?: string; category: string; tags?: string[] } | null> {
  const { readdir } = await import('node:fs/promises')
  let cats: string[]
  try {
    cats = (await readdir(SECTIONS_DIR, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  } catch {
    return null
  }
  for (const cat of cats) {
    try {
      const yamlPath = resolve(SECTIONS_DIR, cat, id, 'section.yaml')
      const raw = await readFile(yamlPath, 'utf-8')
      const m = parseYaml(raw) as Record<string, unknown>
      return {
        id: String(m.id ?? id),
        displayName: String(m.displayName ?? id),
        description: m.description ? String(m.description) : undefined,
        category: cat,
        tags: Array.isArray(m.tags) ? (m.tags as string[]) : undefined,
      }
    } catch {
      continue
    }
  }
  return null
}

/** Map category → visual identity. */
function categoryStyle(cat: string): { accent: string; emoji: string; gradient: [string, string] } {
  const map: Record<string, { accent: string; emoji: string; gradient: [string, string] }> = {
    hero: { accent: '#6366f1', emoji: '🎯', gradient: ['#6366f1', '#ec4899'] },
    features: { accent: '#a855f7', emoji: '✨', gradient: ['#a855f7', '#6366f1'] },
    pricing: { accent: '#22c55e', emoji: '💰', gradient: ['#22c55e', '#10b981'] },
    cta: { accent: '#ec4899', emoji: '👉', gradient: ['#ec4899', '#f97316'] },
    footer: { accent: '#64748b', emoji: '⬇', gradient: ['#475569', '#1e293b'] },
    header: { accent: '#0ea5e9', emoji: '⬆', gradient: ['#0ea5e9', '#6366f1'] },
    testimonials: { accent: '#facc15', emoji: '⭐', gradient: ['#facc15', '#f97316'] },
    logos: { accent: '#94a3b8', emoji: '🏢', gradient: ['#94a3b8', '#475569'] },
    faq: { accent: '#06b6d4', emoji: '❓', gradient: ['#06b6d4', '#3b82f6'] },
    gallery: { accent: '#f97316', emoji: '🖼', gradient: ['#f97316', '#ec4899'] },
    stats: { accent: '#10b981', emoji: '📊', gradient: ['#10b981', '#06b6d4'] },
    team: { accent: '#8b5cf6', emoji: '👥', gradient: ['#8b5cf6', '#a855f7'] },
    content: { accent: '#475569', emoji: '📝', gradient: ['#475569', '#0f172a'] },
    forms: { accent: '#3b82f6', emoji: '✍', gradient: ['#3b82f6', '#6366f1'] },
    blog: { accent: '#7c3aed', emoji: '📰', gradient: ['#7c3aed', '#a855f7'] },
    newsletter: { accent: '#0891b2', emoji: '📧', gradient: ['#0891b2', '#06b6d4'] },
    nav: { accent: '#475569', emoji: '☰', gradient: ['#475569', '#1e293b'] },
    product: { accent: '#db2777', emoji: '🛍', gradient: ['#db2777', '#ec4899'] },
    '3d': { accent: '#a855f7', emoji: '⬢', gradient: ['#a855f7', '#7c3aed'] },
    illustration: { accent: '#f59e0b', emoji: '🎨', gradient: ['#f59e0b', '#f97316'] },
  }
  return map[cat] ?? { accent: '#6366f1', emoji: '✨', gradient: ['#6366f1', '#ec4899'] }
}

/** Escape XML text for SVG content. */
function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

/**
 * Deterministic small hash for a section id — used to vary cards
 * within the same category so 40 3D sections don't all look identical.
 * Returns a stable integer 0..n-1.
 */
function hashOf(s: string): number {
  let h = 0
  for (let i = 0; i < s.length; i++) h = (h * 31 + s.charCodeAt(i)) | 0
  return Math.abs(h)
}

/** Shift an HSL-like accent by a hue delta to give each card a unique tint. */
function shiftedAccent(baseHex: string, deg: number): string {
  // Parse #rrggbb → r,g,b → HSL → shift hue → back to hex.
  const r = parseInt(baseHex.slice(1, 3), 16) / 255
  const g = parseInt(baseHex.slice(3, 5), 16) / 255
  const b = parseInt(baseHex.slice(5, 7), 16) / 255
  const max = Math.max(r, g, b), min = Math.min(r, g, b)
  const l = (max + min) / 2
  let h = 0, sat = 0
  if (max !== min) {
    const d = max - min
    sat = l > 0.5 ? d / (2 - max - min) : d / (max + min)
    switch (max) {
      case r: h = (g - b) / d + (g < b ? 6 : 0); break
      case g: h = (b - r) / d + 2; break
      case b: h = (r - g) / d + 4; break
    }
    h *= 60
  }
  h = (h + deg + 360) % 360
  // HSL → RGB
  const c = (1 - Math.abs(2 * l - 1)) * sat
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1))
  const m = l - c / 2
  let rr = 0, gg = 0, bb = 0
  if (h < 60)       { rr = c; gg = x; bb = 0 }
  else if (h < 120) { rr = x; gg = c; bb = 0 }
  else if (h < 180) { rr = 0; gg = c; bb = x }
  else if (h < 240) { rr = 0; gg = x; bb = c }
  else if (h < 300) { rr = x; gg = 0; bb = c }
  else              { rr = c; gg = 0; bb = x }
  const toHex = (v: number) => Math.round((v + m) * 255).toString(16).padStart(2, '0')
  return `#${toHex(rr)}${toHex(gg)}${toHex(bb)}`
}

/** Pick a deterministic emoji variant for the section within its category. */
const ICON_VARIANTS: Record<string, string[]> = {
  '3d': ['⬢', '◈', '◉', '✦', '⬡', '✺', '✸', '✷', '✶', '✹'],
  hero: ['🎯', '🚀', '⚡', '🌟', '🔥'],
  features: ['✨', '💎', '🔮', '🪄', '⚙'],
  pricing: ['💰', '🪙', '💎', '🏷', '🧾'],
  cta: ['👉', '🎬', '🔔', '⚡', '🎯'],
  footer: ['⬇', '◽', '▤', '═', '⫝'],
  header: ['⬆', '═', '▥', '◽', '⏐'],
  testimonials: ['⭐', '💬', '🗨', '💭', '🏅'],
  faq: ['❓', '💡', '📖', '🔍', '❔'],
  blog: ['📰', '📝', '📖', '✍', '📑'],
  newsletter: ['📧', '✉', '📩', '📬', '📫'],
  nav: ['☰', '⊟', '⫙', '▤', '═'],
  product: ['🛍', '📦', '🏷', '🎁', '🛒'],
  gallery: ['🖼', '🎨', '📷', '🖌', '✏'],
  forms: ['✍', '📝', '☑', '📋', '✅'],
  team: ['👥', '🧑‍🤝‍🧑', '👤', '🫂', '🤝'],
  stats: ['📊', '📈', '🔢', '💹', '🧮'],
  contact: ['✉', '📞', '💌', '📭', '☎'],
  modal: ['⬛', '◾', '▣', '□', '◰'],
}

/**
 * Per-category mini-mockup SVG fragment. Approximates the typical
 * visual shape of sections in that category so the user can tell at
 * a glance "this is a hero" vs "this is a pricing table" without
 * needing real screenshots (Sprint 3).
 *
 * All shapes draw inside the 14-14-346-226 panel area.
 */
function categoryShape(cat: string, accent: string): string {
  const a = accent
  const dim = `${a}55`
  const faint = `${a}22`
  switch (cat) {
    case 'hero':
      // Big centered headline bar + subtitle + dual buttons
      return `
        <rect x="60"  y="62"  width="240" height="14" rx="3" fill="${a}"/>
        <rect x="80"  y="84"  width="200" height="8"  rx="2" fill="${dim}"/>
        <rect x="100" y="98"  width="160" height="6"  rx="2" fill="${faint}"/>
        <rect x="120" y="120" width="50"  height="20" rx="10" fill="${a}"/>
        <rect x="180" y="120" width="50"  height="20" rx="10" fill="none" stroke="${a}" stroke-width="1.5"/>`
    case 'features':
      // 3-cell feature grid with icon dots + caption bars
      return `
        ${[0, 1, 2].map((i) => {
          const x = 50 + i * 88
          return `
            <rect x="${x}" y="78"  width="68" height="68" rx="6" fill="${faint}"/>
            <circle cx="${x + 14}" cy="92" r="6" fill="${a}"/>
            <rect x="${x + 8}" y="108" width="52" height="6" rx="2" fill="${dim}"/>
            <rect x="${x + 8}" y="120" width="40" height="4" rx="2" fill="${faint}"/>
            <rect x="${x + 8}" y="128" width="48" height="4" rx="2" fill="${faint}"/>`
        }).join('')}`
    case 'pricing':
      // 3 pricing tiers with middle highlighted
      return `
        ${[0, 1, 2].map((i) => {
          const x = 38 + i * 100
          const hi = i === 1
          return `
            <rect x="${x}" y="64" width="80" height="100" rx="8" fill="${hi ? a : 'none'}" fill-opacity="${hi ? 0.25 : 1}" stroke="${a}" stroke-width="${hi ? 2 : 1}"/>
            <rect x="${x + 14}" y="74" width="40" height="8" rx="2" fill="${a}"/>
            <rect x="${x + 14}" y="88" width="52" height="14" rx="2" fill="${a}"/>
            <rect x="${x + 14}" y="108" width="48" height="4" rx="2" fill="${dim}"/>
            <rect x="${x + 14}" y="116" width="44" height="4" rx="2" fill="${dim}"/>
            <rect x="${x + 14}" y="124" width="48" height="4" rx="2" fill="${dim}"/>
            <rect x="${x + 14}" y="142" width="52" height="12" rx="6" fill="${hi ? a : 'none'}" stroke="${a}" stroke-width="1"/>`
        }).join('')}`
    case 'cta':
      // Centered headline + giant button
      return `
        <rect x="80"  y="78"  width="200" height="14" rx="3" fill="${a}"/>
        <rect x="110" y="100" width="140" height="6"  rx="2" fill="${dim}"/>
        <rect x="130" y="124" width="100" height="28" rx="14" fill="${a}"/>`
    case 'footer':
      // Wide bottom row with brand block + columns
      return `
        <rect x="40"  y="80"  width="280" height="80" rx="6" fill="${faint}"/>
        <rect x="56"  y="92"  width="60"  height="10" rx="2" fill="${a}"/>
        <rect x="56"  y="106" width="100" height="4"  rx="2" fill="${dim}"/>
        <rect x="56"  y="114" width="90"  height="4"  rx="2" fill="${dim}"/>
        ${[0, 1, 2].map((i) => {
          const x = 180 + i * 50
          return `
            <rect x="${x}" y="92"  width="40" height="6" rx="2" fill="${a}"/>
            <rect x="${x}" y="104" width="36" height="3" rx="1" fill="${dim}"/>
            <rect x="${x}" y="112" width="32" height="3" rx="1" fill="${dim}"/>
            <rect x="${x}" y="120" width="34" height="3" rx="1" fill="${dim}"/>`
        }).join('')}`
    case 'header':
      // Top nav bar with brand + links + cta
      return `
        <rect x="30" y="74" width="300" height="36" rx="6" fill="${faint}"/>
        <rect x="42" y="86" width="50" height="12" rx="2" fill="${a}"/>
        <rect x="140" y="89" width="28" height="6" rx="2" fill="${dim}"/>
        <rect x="178" y="89" width="28" height="6" rx="2" fill="${dim}"/>
        <rect x="216" y="89" width="28" height="6" rx="2" fill="${dim}"/>
        <rect x="266" y="82" width="54" height="20" rx="10" fill="${a}"/>`
    case 'testimonials':
      // 2 quote cards with author dots
      return `
        ${[0, 1].map((i) => {
          const x = 38 + i * 144
          return `
            <rect x="${x}" y="66" width="140" height="100" rx="8" fill="${faint}"/>
            <rect x="${x + 12}" y="78"  width="116" height="5" rx="2" fill="${dim}"/>
            <rect x="${x + 12}" y="88"  width="104" height="5" rx="2" fill="${dim}"/>
            <rect x="${x + 12}" y="98"  width="92"  height="5" rx="2" fill="${dim}"/>
            <circle cx="${x + 24}" cy="138" r="9" fill="${a}"/>
            <rect x="${x + 38}" y="132" width="48" height="6" rx="2" fill="${a}"/>
            <rect x="${x + 38}" y="142" width="38" height="4" rx="2" fill="${dim}"/>`
        }).join('')}`
    case 'faq':
      // Stacked accordion rows
      return `
        ${[0, 1, 2, 3].map((i) => {
          const y = 60 + i * 24
          return `
            <rect x="50" y="${y}" width="260" height="18" rx="4" fill="${faint}"/>
            <rect x="62" y="${y + 6}" width="180" height="6" rx="2" fill="${a}"/>
            <text x="298" y="${y + 13}" font-size="11" fill="${dim}">+</text>`
        }).join('')}`
    case 'blog':
      // Featured post + 2 teasers
      return `
        <rect x="40" y="62" width="280" height="60" rx="6" fill="${faint}"/>
        <rect x="56" y="76" width="120" height="10" rx="2" fill="${a}"/>
        <rect x="56" y="92" width="160" height="5" rx="2" fill="${dim}"/>
        <rect x="56" y="102" width="140" height="5" rx="2" fill="${dim}"/>
        ${[0, 1].map((i) => {
          const x = 40 + i * 144
          return `
            <rect x="${x}" y="130" width="136" height="36" rx="4" fill="${faint}"/>
            <rect x="${x + 12}" y="138" width="90" height="6" rx="2" fill="${a}"/>
            <rect x="${x + 12}" y="150" width="100" height="4" rx="2" fill="${dim}"/>`
        }).join('')}`
    case 'pricing': // already handled above (case 'pricing'), fallthrough won't reach
    case 'nav':
      // Top nav like header
      return `
        <rect x="30" y="74" width="300" height="36" rx="6" fill="${faint}"/>
        <rect x="42" y="86" width="50" height="12" rx="2" fill="${a}"/>
        <rect x="266" y="82" width="54" height="20" rx="10" fill="${a}"/>`
    case 'gallery':
      // Masonry grid
      return `
        <rect x="40"  y="60" width="84" height="50" rx="4" fill="${faint}"/>
        <rect x="130" y="60" width="84" height="70" rx="4" fill="${faint}"/>
        <rect x="220" y="60" width="100" height="50" rx="4" fill="${faint}"/>
        <rect x="40"  y="118" width="84" height="50" rx="4" fill="${faint}"/>
        <rect x="220" y="118" width="100" height="50" rx="4" fill="${faint}"/>`
    case 'forms':
    case 'contact':
      // Form fields stacked
      return `
        <rect x="80" y="58" width="200" height="10" rx="2" fill="${a}"/>
        <rect x="80" y="78" width="200" height="22" rx="4" fill="${faint}"/>
        <rect x="80" y="108" width="200" height="22" rx="4" fill="${faint}"/>
        <rect x="80" y="138" width="200" height="22" rx="4" fill="${faint}"/>
        <rect x="80" y="170" width="200" height="22" rx="11" fill="${a}"/>`
    case 'stats':
      // 4 big numbers in a row
      return `
        ${[0, 1, 2, 3].map((i) => {
          const x = 40 + i * 75
          return `
            <rect x="${x}" y="78"  width="60" height="22" rx="3" fill="${a}"/>
            <rect x="${x}" y="106" width="50" height="5"  rx="2" fill="${dim}"/>
            <rect x="${x}" y="116" width="40" height="4"  rx="2" fill="${faint}"/>`
        }).join('')}`
    case 'team':
      // 4 avatar circles + caption
      return `
        ${[0, 1, 2, 3].map((i) => {
          const x = 60 + i * 65
          return `
            <circle cx="${x + 18}" cy="92" r="20" fill="${faint}"/>
            <rect x="${x + 4}" y="124" width="32" height="6" rx="2" fill="${a}"/>
            <rect x="${x + 7}" y="134" width="26" height="4" rx="2" fill="${dim}"/>`
        }).join('')}`
    case 'logos':
      // Logo wall
      return `
        ${[0, 1, 2, 3, 4].map((i) => {
          const x = 30 + i * 62
          return `<rect x="${x}" y="100" width="50" height="22" rx="4" fill="${faint}"/>`
        }).join('')}`
    case 'product':
      // Product image + price + cta
      return `
        <rect x="38" y="60" width="120" height="120" rx="6" fill="${faint}"/>
        <rect x="172" y="72"  width="140" height="12" rx="2" fill="${a}"/>
        <rect x="172" y="92"  width="60"  height="14" rx="2" fill="${a}"/>
        <rect x="172" y="114" width="140" height="5"  rx="2" fill="${dim}"/>
        <rect x="172" y="124" width="120" height="5"  rx="2" fill="${dim}"/>
        <rect x="172" y="144" width="100" height="22" rx="11" fill="${a}"/>`
    case '3d':
      // 3D-ish shape — animated-feeling concentric polys
      return `
        <g transform="translate(180 115)" stroke="${a}" stroke-width="1.5" fill="none" opacity="0.85">
          <polygon points="-50,0 -25,-40 25,-40 50,0 25,40 -25,40" fill="${faint}"/>
          <polygon points="-32,0 -16,-26 16,-26 32,0 16,26 -16,26"/>
          <polygon points="-16,0 -8,-13 8,-13 16,0 8,13 -8,13" fill="${a}" fill-opacity="0.6"/>
        </g>`
    case 'banner':
    case 'notice':
      // Wide notification bar
      return `
        <rect x="30" y="100" width="300" height="40" rx="6" fill="${faint}"/>
        <circle cx="56" cy="120" r="8" fill="${a}"/>
        <rect x="76" y="112" width="180" height="6" rx="2" fill="${a}"/>
        <rect x="76" y="124" width="140" height="5" rx="2" fill="${dim}"/>`
    case 'newsletter':
      // Email capture
      return `
        <rect x="80" y="76" width="200" height="10" rx="2" fill="${a}"/>
        <rect x="80" y="100" width="140" height="22" rx="4" fill="${faint}"/>
        <rect x="226" y="100" width="54" height="22" rx="4" fill="${a}"/>`
    case 'timeline':
    case 'process':
      // Horizontal step indicator
      return `
        <line x1="40" y1="115" x2="320" y2="115" stroke="${dim}" stroke-width="2"/>
        ${[0, 1, 2, 3].map((i) => {
          const x = 60 + i * 75
          return `
            <circle cx="${x}" cy="115" r="10" fill="${a}"/>
            <rect x="${x - 18}" y="135" width="36" height="6" rx="2" fill="${dim}"/>`
        }).join('')}`
    case 'modal':
    case 'empty':
      // Centered card
      return `
        <rect x="80" y="60" width="200" height="120" rx="8" fill="${faint}" stroke="${a}" stroke-width="1"/>
        <rect x="100" y="80" width="160" height="10" rx="2" fill="${a}"/>
        <rect x="120" y="100" width="120" height="5" rx="2" fill="${dim}"/>
        <rect x="160" y="148" width="40" height="20" rx="10" fill="${a}"/>`
    case 'breadcrumb':
      return `
        ${[0, 1, 2, 3].map((i) => {
          const x = 50 + i * 70
          return `
            <rect x="${x}" y="115" width="46" height="8" rx="2" fill="${i === 3 ? a : dim}"/>
            ${i < 3 ? `<text x="${x + 52}" y="123" font-size="11" fill="${dim}">›</text>` : ''}`
        }).join('')}`
    case 'divider':
      return `<line x1="60" y1="120" x2="300" y2="120" stroke="${a}" stroke-width="2"/>`
    case 'sidebar':
      return `
        <rect x="40"  y="60" width="80"  height="120" rx="6" fill="${faint}"/>
        <rect x="130" y="60" width="190" height="120" rx="6" fill="${faint}"/>
        ${[0, 1, 2, 3].map((i) => `<rect x="50" y="${72 + i * 22}" width="60" height="10" rx="2" fill="${dim}"/>`).join('')}`
    case 'charts':
    case 'metric':
      // Bar chart
      return `
        ${[40, 70, 30, 90, 55, 80, 45].map((h, i) => `
          <rect x="${50 + i * 38}" y="${170 - h}" width="22" height="${h}" rx="2" fill="${a}" fill-opacity="${0.4 + (i % 3) * 0.2}"/>`).join('')}`
    case 'content':
      // Article body paragraphs
      return `
        <rect x="50" y="62" width="180" height="12" rx="2" fill="${a}"/>
        ${[0, 1, 2, 3, 4, 5].map((i) => `
          <rect x="50" y="${88 + i * 13}" width="${200 + ((i * 47) % 60)}" height="5" rx="2" fill="${dim}"/>`).join('')}`
    default:
      // Generic block + lines fallback
      return `
        <rect x="60" y="70" width="240" height="16" rx="3" fill="${a}"/>
        <rect x="80" y="100" width="200" height="6" rx="2" fill="${dim}"/>
        <rect x="80" y="114" width="170" height="6" rx="2" fill="${dim}"/>
        <rect x="140" y="140" width="80" height="22" rx="11" fill="${a}"/>`
  }
}

function buildSvg(section: { id: string; displayName: string; category: string }): string {
  const style = categoryStyle(section.category)
  // Per-section variation: stable hash → hue shift (-30°…+30°), emoji
  // variant from the category's pool, decorative dot pattern offset.
  const h = hashOf(section.id)
  const hueShift = ((h % 61) - 30) // -30..+30
  const accent = shiftedAccent(style.accent, hueShift)
  const accent2 = shiftedAccent(style.gradient[1], -hueShift)
  const variants = ICON_VARIANTS[section.category] ?? [style.emoji]
  const emoji = variants[h % variants.length]!

  // For small palette cards, the display name is the most-readable signal.
  // Strip the redundant category prefix ("3D hover-flip tile" → "hover-flip tile")
  // and uppercase for impact. Limit to 28 chars total.
  const cleanName = section.displayName.replace(new RegExp(`^${section.category}\\s+`, 'i'), '')
  const big = cleanName.length > 28 ? cleanName.slice(0, 25) + '…' : cleanName
  // Show full original name in the bottom bar
  const display = section.displayName.length > 28 ? section.displayName.slice(0, 25) + '…' : section.displayName

  // 360x240 — 3:2, matches Canva-ish thumbnail ratio.
  return `<svg xmlns="http://www.w3.org/2000/svg" width="360" height="240" viewBox="0 0 360 240">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#020617"/>
    </linearGradient>
    <linearGradient id="bigtext" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${accent}" stop-opacity="0.85"/>
      <stop offset="100%" stop-color="${accent2}" stop-opacity="0.85"/>
    </linearGradient>
    <radialGradient id="glow" cx="${20 + (h % 60)}%" cy="${20 + ((h >> 8) % 50)}%" r="60%">
      <stop offset="0%" stop-color="${accent}" stop-opacity="0.45"/>
      <stop offset="100%" stop-color="${accent}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="360" height="240" fill="url(#bg)"/>
  <rect width="360" height="240" fill="url(#glow)"/>
  <rect x="14" y="14" width="332" height="212" rx="14" fill="none" stroke="rgba(255,255,255,0.10)" stroke-width="1"/>

  <!-- Top meta strip -->
  <g transform="translate(28, 28)">
    <rect width="74" height="20" rx="10" fill="${accent}" fill-opacity="0.22"/>
    <text x="37" y="14" text-anchor="middle" fill="${accent}" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="9" font-weight="700" letter-spacing="1">${xml(section.category.toUpperCase())}</text>
  </g>
  <text x="338" y="42" text-anchor="end" font-size="20" opacity="0.55">${emoji}</text>

  <!-- BIG section name — the dominant visual signal at small card sizes -->
  <text x="180" y="125" text-anchor="middle" fill="url(#bigtext)" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="${big.length > 18 ? 26 : 34}" font-weight="800" letter-spacing="-0.5">${xml(big)}</text>

  <!-- Tiny mini-mockup, dimmed, behind the big text -->
  <g opacity="0.30">${categoryShape(section.category, accent2)}</g>

  <!-- Bottom bar: full display name + id -->
  <rect x="14" y="195" width="332" height="31" fill="rgba(0,0,0,0.55)"/>
  <text x="28" y="213" fill="#fff" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="12" font-weight="700">${xml(display)}</text>
  <text x="28" y="222" fill="rgba(255,255,255,0.4)" font-family="ui-monospace, Menlo, monospace" font-size="9">${xml(section.id)}</text>
</svg>`
}

export async function GET(_req: Request, ctx: Params) {
  const { id } = await ctx.params
  if (!/^[A-Za-z][A-Za-z0-9-]*$/.test(id)) {
    return NextResponse.json({ error: 'invalid id' }, { status: 400 })
  }

  // 1. PNG cache (Sprint 1b will populate these via Playwright).
  const pngPath = resolve(PUBLIC_THUMBS, `${id}.png`)
  try {
    const st = await stat(pngPath)
    if (st.isFile()) {
      const buf = await readFile(pngPath)
      return new NextResponse(buf as unknown as BodyInit, {
        headers: {
          'content-type': 'image/png',
          'cache-control': 'public, max-age=86400, immutable',
        },
      })
    }
  } catch {
    // fall through to SVG
  }

  // 2. Generated SVG card.
  const section = await findSection(id)
  if (!section) {
    return NextResponse.json({ error: 'not found' }, { status: 404 })
  }
  const svg = buildSvg(section)
  return new NextResponse(svg, {
    headers: {
      'content-type': 'image/svg+xml; charset=utf-8',
      'cache-control': 'public, max-age=86400',
    },
  })
}
