/**
 * GET /api/sections/thumbnail/<id>
 *
 * Returns a thumbnail image for one section.
 *
 * Sprint 1a (now): SVG card with section accent + category icon + name
 *   — visually scannable in the palette, no Playwright needed.
 * Sprint 1b (next commit): real PNG screenshot generated by Playwright
 *   against a live running generated app. Cached PNGs at
 *   apps/studio/public/thumbnails/<id>.png — if present they win.
 *
 * Cache header set to 1 day for SVGs (regenerate cheap if catalog adds
 * sections). PNG cache served by Next's static-file middleware.
 */
import { NextResponse } from 'next/server'
import { readFile, stat } from 'node:fs/promises'
import { resolve } from 'node:path'
import { parse as parseYaml } from 'yaml'

const PROJECT_ROOT = resolve(process.cwd(), '..', '..')
const SECTIONS_DIR = resolve(PROJECT_ROOT, 'sections')
const PUBLIC_THUMBS = resolve(process.cwd(), 'public', 'thumbnails')

type Params = { params: Promise<{ id: string }> }

/** Loose lookup: scan sections/<category>/<id>/section.yaml until match. */
async function findSection(id: string): Promise<{ id: string; displayName: string; description?: string; category: string; tags?: string[] } | null> {
  const { readdir } = await import('node:fs/promises')
  let cats: string[]
  try {
    cats = (await readdir(SECTIONS_DIR, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  } catch {
    return null
  }
  for (const cat of cats) {
    try {
      const yamlPath = resolve(SECTIONS_DIR, cat, id, 'section.yaml')
      const raw = await readFile(yamlPath, 'utf-8')
      const m = parseYaml(raw) as Record<string, unknown>
      return {
        id: String(m.id ?? id),
        displayName: String(m.displayName ?? id),
        description: m.description ? String(m.description) : undefined,
        category: cat,
        tags: Array.isArray(m.tags) ? (m.tags as string[]) : undefined,
      }
    } catch {
      continue
    }
  }
  return null
}

/** Map category → visual identity. */
function categoryStyle(cat: string): { accent: string; emoji: string; gradient: [string, string] } {
  const map: Record<string, { accent: string; emoji: string; gradient: [string, string] }> = {
    hero: { accent: '#6366f1', emoji: '🎯', gradient: ['#6366f1', '#ec4899'] },
    features: { accent: '#a855f7', emoji: '✨', gradient: ['#a855f7', '#6366f1'] },
    pricing: { accent: '#22c55e', emoji: '💰', gradient: ['#22c55e', '#10b981'] },
    cta: { accent: '#ec4899', emoji: '👉', gradient: ['#ec4899', '#f97316'] },
    footer: { accent: '#64748b', emoji: '⬇', gradient: ['#475569', '#1e293b'] },
    header: { accent: '#0ea5e9', emoji: '⬆', gradient: ['#0ea5e9', '#6366f1'] },
    testimonials: { accent: '#facc15', emoji: '⭐', gradient: ['#facc15', '#f97316'] },
    logos: { accent: '#94a3b8', emoji: '🏢', gradient: ['#94a3b8', '#475569'] },
    faq: { accent: '#06b6d4', emoji: '❓', gradient: ['#06b6d4', '#3b82f6'] },
    gallery: { accent: '#f97316', emoji: '🖼', gradient: ['#f97316', '#ec4899'] },
    stats: { accent: '#10b981', emoji: '📊', gradient: ['#10b981', '#06b6d4'] },
    team: { accent: '#8b5cf6', emoji: '👥', gradient: ['#8b5cf6', '#a855f7'] },
    content: { accent: '#475569', emoji: '📝', gradient: ['#475569', '#0f172a'] },
    forms: { accent: '#3b82f6', emoji: '✍', gradient: ['#3b82f6', '#6366f1'] },
    blog: { accent: '#7c3aed', emoji: '📰', gradient: ['#7c3aed', '#a855f7'] },
    newsletter: { accent: '#0891b2', emoji: '📧', gradient: ['#0891b2', '#06b6d4'] },
    nav: { accent: '#475569', emoji: '☰', gradient: ['#475569', '#1e293b'] },
    product: { accent: '#db2777', emoji: '🛍', gradient: ['#db2777', '#ec4899'] },
    '3d': { accent: '#a855f7', emoji: '⬢', gradient: ['#a855f7', '#7c3aed'] },
    illustration: { accent: '#f59e0b', emoji: '🎨', gradient: ['#f59e0b', '#f97316'] },
  }
  return map[cat] ?? { accent: '#6366f1', emoji: '✨', gradient: ['#6366f1', '#ec4899'] }
}

/** Escape XML text for SVG content. */
function xml(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

function buildSvg(section: { id: string; displayName: string; category: string }): string {
  const style = categoryStyle(section.category)
  const display = section.displayName.length > 38 ? section.displayName.slice(0, 35) + '…' : section.displayName
  // 360x240 — 3:2, matches Canva-ish thumbnail ratio.
  return `<svg xmlns="http://www.w3.org/2000/svg" width="360" height="240" viewBox="0 0 360 240">
  <defs>
    <linearGradient id="g" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="${style.gradient[0]}"/>
      <stop offset="100%" stop-color="${style.gradient[1]}"/>
    </linearGradient>
    <linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">
      <stop offset="0%" stop-color="#0f172a"/>
      <stop offset="100%" stop-color="#020617"/>
    </linearGradient>
    <radialGradient id="glow" cx="50%" cy="40%" r="60%">
      <stop offset="0%" stop-color="${style.accent}" stop-opacity="0.45"/>
      <stop offset="100%" stop-color="${style.accent}" stop-opacity="0"/>
    </radialGradient>
  </defs>
  <rect width="360" height="240" fill="url(#bg)"/>
  <rect width="360" height="240" fill="url(#glow)"/>
  <rect x="14" y="14" width="332" height="212" rx="14" fill="none" stroke="rgba(255,255,255,0.08)" stroke-width="1"/>
  <!-- Accent band top -->
  <rect x="14" y="14" width="332" height="3" rx="1.5" fill="url(#g)"/>
  <!-- Category chip -->
  <g transform="translate(28, 32)">
    <rect width="92" height="22" rx="11" fill="${style.accent}" fill-opacity="0.18"/>
    <text x="46" y="15" text-anchor="middle" fill="${style.accent}" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="10" font-weight="700" letter-spacing="1.2">${xml(section.category.toUpperCase())}</text>
  </g>
  <!-- Big emoji -->
  <text x="180" y="135" text-anchor="middle" font-size="64" opacity="0.55">${style.emoji}</text>
  <!-- Display name -->
  <text x="180" y="186" text-anchor="middle" fill="#fff" font-family="-apple-system, BlinkMacSystemFont, Segoe UI, sans-serif" font-size="14" font-weight="700">${xml(display)}</text>
  <!-- ID -->
  <text x="180" y="206" text-anchor="middle" fill="rgba(255,255,255,0.4)" font-family="ui-monospace, Menlo, monospace" font-size="10">${xml(section.id)}</text>
</svg>`
}

export async function GET(_req: Request, ctx: Params) {
  const { id } = await ctx.params
  if (!/^[A-Za-z][A-Za-z0-9-]*$/.test(id)) {
    return NextResponse.json({ error: 'invalid id' }, { status: 400 })
  }

  // 1. PNG cache (Sprint 1b will populate these via Playwright).
  const pngPath = resolve(PUBLIC_THUMBS, `${id}.png`)
  try {
    const st = await stat(pngPath)
    if (st.isFile()) {
      const buf = await readFile(pngPath)
      return new NextResponse(buf as unknown as BodyInit, {
        headers: {
          'content-type': 'image/png',
          'cache-control': 'public, max-age=86400, immutable',
        },
      })
    }
  } catch {
    // fall through to SVG
  }

  // 2. Generated SVG card.
  const section = await findSection(id)
  if (!section) {
    return NextResponse.json({ error: 'not found' }, { status: 404 })
  }
  const svg = buildSvg(section)
  return new NextResponse(svg, {
    headers: {
      'content-type': 'image/svg+xml; charset=utf-8',
      'cache-control': 'public, max-age=86400',
    },
  })
}
