import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { scanThemes } from '../src/load.js'
import { deriveTailwindConfig } from '../src/render/derive-tailwind-config.js'

const HERE = dirname(fileURLToPath(import.meta.url))
const REPO_THEMES = resolve(HERE, '../../../themes')

describe('deriveTailwindConfig', () => {
  let outDir: string

  beforeEach(async () => {
    outDir = await mkdtemp(join(tmpdir(), 'wirer-tw-'))
  })

  afterEach(async () => {
    await rm(outDir, { recursive: true, force: true })
  })

  it('emits numeric color scales + fontFamily + spacing from theme tokens', async () => {
    const themes = await scanThemes(REPO_THEMES)
    const minimal = themes.find((t) => t.pack === 'minimal')!

    const dest = await deriveTailwindConfig({
      theme: minimal,
      outputDir: outDir,
    })
    const content = await readFile(dest, 'utf-8')

    // Header references theme pack
    expect(content).toContain('Generated by b-dash from theme: minimal')
    // CSS-var semantic palette retained
    expect(content).toContain("border: 'hsl(var(--border))'")
    expect(content).toContain("DEFAULT: 'hsl(var(--primary))'")
    // Numeric scale from tokens.json injected under primary
    expect(content).toMatch(/'500': '#0ea5e9'/)
    expect(content).toMatch(/'950': '#082f49'/)
    // Accent + neutral scales emitted
    expect(content).toMatch(/'500': '#d946ef'/)
    expect(content).toMatch(/'500': '#737373'/)
    // Semantic colors flattened (success-bg, warning-fg, ...)
    expect(content).toMatch(/'success-bg': '#dcfce7'/)
    expect(content).toMatch(/'error-fg': '#991b1b'/)
    // Font family derived from fontPair shorthand
    expect(content).toContain("sans: ['Geist'")
    expect(content).toContain("mono: ['JetBrains Mono'")
    // Spacing carried through
    expect(content).toContain("'4': '1rem'")
    // Border radius from tokens (literal values, not CSS vars when tokens present)
    expect(content).toContain("lg: '0.5rem'")
    expect(content).toContain("'2xl': '1rem'")
    expect(content).toContain("full: '9999px'")
  })
})
