/**
 * Compose a real homepage from `recipe.sections`.
 *
 * Plan §19.1 step 8 — "APPLY PAGES". Without this step the generated
 * frontend ships only the scaffold's `Hello.` placeholder and the
 * copied section components sit orphaned in `src/sections/`.
 *
 * This step generates `<out>/frontend/src/app/page.tsx` that:
 *   - Imports each section component listed in `recipe.sections`
 *   - Renders them top-to-bottom with realistic demo props
 *   - Threads `recipe.branding` (name + tagline + primary colour) into
 *     the hero / header / footer so the page actually says the user's
 *     app name instead of "Generated by b-dash."
 *
 * If `recipe.sections` is absent or empty, the scaffold's placeholder
 * `page.tsx` stays untouched (back-compat for non-wizard recipes).
 */
import { mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { parse as parseYaml } from 'yaml'
import type { WirePlan } from '../types.js'

export type Branding = {
  name: string
  tagline?: string
  primary?: string
}

export type DerivePageArgs = {
  plan: WirePlan
  outputDir: string
  /** Absolute path to the catalog's sections/ root. Used to read each
   *  section.yaml so derive-page can synthesise safe default props for
   *  sections we don't manually template. */
  sectionsRoot?: string
}

/**
 * Read section.yaml for `sectionId` from the catalog. Returns null
 * if not found. We scan all categories since copy-sections layout is
 * <out>/frontend/src/sections/<id>/ (flat) but the source catalog is
 * sections/<category>/<id>/.
 */
async function readSectionYaml(
  sectionsRoot: string,
  sectionId: string,
): Promise<{ props?: Record<string, { type?: string; default?: unknown; required?: boolean }> } | null> {
  let cats: string[]
  try {
    cats = (await readdir(sectionsRoot, { withFileTypes: true }))
      .filter((e) => e.isDirectory())
      .map((e) => e.name)
  } catch {
    return null
  }
  for (const cat of cats) {
    const p = path.join(sectionsRoot, cat, sectionId, 'section.yaml')
    try {
      const raw = await readFile(p, 'utf-8')
      return parseYaml(raw) as { props?: Record<string, { type?: string; default?: unknown; required?: boolean }> }
    } catch {
      // not in this category
    }
  }
  return null
}

/**
 * Pick a safe placeholder value for a single prop based on its
 * declared type. Used when no manual SECTION_PROPS entry exists.
 */
function safeDefaultValue(type: string | undefined, name: string): unknown {
  switch (type) {
    case 'number': return 0
    case 'boolean': case 'bool': return false
    case 'color': return '#6366f1'
    case 'image': return ''
    case 'array': {
      // Provide 3 sample items so .map() works. Common shape: { title, body }.
      // We don't know the inner shape — provide a generic object with common keys.
      return [
        { title: 'Sample 1', subtitle: 'Sample 1 detail', body: 'Sample 1 body', label: 'Sample 1', name: 'Sample 1', icon: '✨', href: '#', text: 'Sample 1', value: 'Sample 1' },
        { title: 'Sample 2', subtitle: 'Sample 2 detail', body: 'Sample 2 body', label: 'Sample 2', name: 'Sample 2', icon: '⚡', href: '#', text: 'Sample 2', value: 'Sample 2' },
        { title: 'Sample 3', subtitle: 'Sample 3 detail', body: 'Sample 3 body', label: 'Sample 3', name: 'Sample 3', icon: '🎯', href: '#', text: 'Sample 3', value: 'Sample 3' },
      ]
    }
    case 'json': case 'object': return {}
    case 'string': default:
      return name.toLowerCase().includes('href') || name.toLowerCase().includes('url') ? '#' : `Sample ${name}`
  }
}

/**
 * Synthesise a complete safe-defaults object literal for a section
 * we don't manually template. Reads section.yaml + branding.
 */
async function synthesiseDefaults(
  sectionsRoot: string,
  sectionId: string,
  branding: Branding,
): Promise<string> {
  const yaml = await readSectionYaml(sectionsRoot, sectionId)
  if (!yaml || !yaml.props) {
    // Unknown section + no yaml → return empty obj; will likely render
    // a tiny "no props" section but won't crash.
    return '{}'
  }
  const entries: string[] = []
  for (const [name, schema] of Object.entries(yaml.props)) {
    // Prefer the yaml's `default` if declared, otherwise synthesise.
    const value = schema.default !== undefined
      ? schema.default
      : safeDefaultValue(schema.type, name)
    // Wire branding fields to obvious slots.
    let final: unknown = value
    if ((name === 'brandName' || name === 'name' || name === 'headline' || name === 'title') && value === safeDefaultValue(schema.type, name)) {
      final = branding.name
    } else if ((name === 'tagline' || name === 'body' || name === 'subhead') && value === safeDefaultValue(schema.type, name)) {
      final = branding.tagline || `${branding.name} — built with B-Dash.`
    } else if ((name === 'accentColor' || name === 'color' || name === 'primary') && schema.type === 'color') {
      final = branding.primary || '#6366f1'
    }
    entries.push(`    ${JSON.stringify(name)}: ${JSON.stringify(final)}`)
  }
  return `{\n${entries.join(',\n')},\n  }`
}

/**
 * Per-section demo props. Keyed by section id. Each value is a JS
 * expression rendered into the JSX as `{...obj}` so we can pass arrays
 * of objects safely (no string-escaping headaches).
 *
 * Hero / header / footer entries reference `brandName` / `tagline` which
 * are injected as locals in the generated page.
 */
const SECTION_PROPS: Record<string, (b: Branding) => string> = {
  HeaderMinimal: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    brandHref: '/',
    links: [
      { label: 'Features', href: '#features' },
      { label: 'Pricing', href: '#pricing' },
      { label: 'FAQ', href: '#faq' },
    ],
    ctaLabel: 'Get started',
    ctaHref: '#cta',
  }`,
  HeaderMega: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    columns: [
      { title: 'Product', links: [{ label: 'Features', href: '#features' }] },
      { title: 'Resources', links: [{ label: 'Docs', href: '/docs' }] },
    ],
    ctaLabel: 'Sign up',
    ctaHref: '#cta',
  }`,
  TopNav: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    links: [
      { label: 'Home', href: '/' },
      { label: 'About', href: '/about' },
    ],
  }`,

  HeroCentered: (b) => `{
    eyebrow: 'Welcome',
    headline: ${JSON.stringify(b.name)},
    body: ${JSON.stringify(b.tagline || 'A modern app built with B-Dash.')},
    ctaLabel: 'Get started',
    ctaHref: '#cta',
    secondaryLabel: 'Learn more',
    secondaryHref: '#features',
  }`,

  FeatureGrid3Col: () => `{
    eyebrow: 'Features',
    headline: 'Everything you need',
    body: 'A focused toolkit that gets out of your way.',
    features: [
      { icon: '⚡', title: 'Fast', body: 'Boots instantly. No bloat.' },
      { icon: '🔒', title: 'Secure', body: 'Sensible defaults baked in.' },
      { icon: '🎨', title: 'Yours', body: 'Own the code. Deploy anywhere.' },
    ],
  }`,

  CompanyWall: () => `{
    heading: 'Loved by teams',
    cells: [
      { logoUrl: '', companyName: 'Acme', quote: 'Game changer.', authorName: 'Ada', authorRole: 'CTO' },
      { logoUrl: '', companyName: 'Globex', quote: 'Shipped in a week.', authorName: 'Ben', authorRole: 'PM' },
      { logoUrl: '', companyName: 'Initech', quote: 'Just works.', authorName: 'Carla', authorRole: 'Eng' },
    ],
  }`,

  PricingCompare: () => `{
    heading: 'Simple pricing',
    columns: [
      { name: 'Free', tagline: 'Try it out', price: '$0', cadence: '/mo',
        ctaLabel: 'Start free', ctaHref: '#', bullets: ['Core features', 'Community support'] },
      { name: 'Pro', tagline: 'For growing teams', price: '$19', cadence: '/mo',
        ctaLabel: 'Start trial', ctaHref: '#', bullets: ['Everything in Free', 'Email support', 'Custom domains'],
        highlight: true },
      { name: 'Team', tagline: 'For scale', price: '$49', cadence: '/mo',
        ctaLabel: 'Contact sales', ctaHref: '#', bullets: ['Everything in Pro', 'SSO', 'Priority SLA'] },
    ],
  }`,

  FaqAccordion: () => `{
    eyebrow: 'FAQ',
    headline: 'Frequently asked questions',
    items: [
      { question: 'Is this free?', answer: 'A free tier is available. Paid plans start at $19/mo.' },
      { question: 'Do I own the code?', answer: 'Yes — the entire codebase is yours to deploy anywhere.' },
      { question: 'Can I customize it?', answer: 'Yes — edit any file, or use overrides/ to preserve changes across regens.' },
    ],
  }`,

  CtaCentered: () => `{
    headline: 'Ready to ship?',
    body: 'Build a working app in minutes — not months.',
    ctaLabel: 'Get started',
    ctaHref: '#',
  }`,

  FooterColumns: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    tagline: ${JSON.stringify(b.tagline || '')},
    columns: [
      { title: 'Product', links: [
        { label: 'Features', href: '#features' },
        { label: 'Pricing', href: '#pricing' },
      ] },
      { title: 'Company', links: [
        { label: 'About', href: '/about' },
        { label: 'Contact', href: '/contact' },
      ] },
      { title: 'Legal', links: [
        { label: 'Privacy', href: '/privacy' },
        { label: 'Terms', href: '/terms' },
      ] },
    ],
    legal: '© 2026 ' + ${JSON.stringify(b.name)},
  }`,

  NewsletterSignup: () => `{
    headline: 'Stay in the loop',
    body: 'One short update per month. No spam, ever.',
    placeholder: 'you@example.com',
    ctaLabel: 'Subscribe',
    actionUrl: '/api/newsletter/subscribe',
  }`,

  BlogHeroFeatured: () => `{
    eyebrow: 'Featured',
    headline: 'Welcome to the blog',
    excerpt: 'Long-form posts on what we are building.',
    href: '/posts/welcome',
    authorName: 'The team',
    publishedAt: 'May 31, 2026',
  }`,

  BlogArchive: () => `{
    heading: 'Archive',
    years: [
      { year: '2026', months: [
        { label: 'May', href: '/blog/2026/05', count: 4 },
        { label: 'April', href: '/blog/2026/04', count: 6 },
      ] },
    ],
  }`,

  BlogCardHorizontal: () => `{
    title: 'Welcome to the blog',
    excerpt: 'Our very first post.',
    href: '/posts/welcome',
    authorName: 'The team',
    publishedAt: 'May 31, 2026',
    imageUrl: '',
  }`,

  CardCarousel: () => `{
    heading: 'Selected work',
    cards: [
      { title: 'Project Alpha', body: 'A polished thing.', imageUrl: '', href: '#' },
      { title: 'Project Beta',  body: 'Another polished thing.', imageUrl: '', href: '#' },
      { title: 'Project Gamma', body: 'Yet another.', imageUrl: '', href: '#' },
    ],
  }`,

  ProductGallery: () => `{
    images: [
      { url: '', alt: 'Product front' },
      { url: '', alt: 'Product side' },
      { url: '', alt: 'Product back' },
    ],
  }`,

  // ── Premium 3D landing sections ──────────────────────────────
  Hero3DScene: (b) => `{
    eyebrow: 'Introducing',
    headline: ${JSON.stringify(b.name)},
    body: ${JSON.stringify(b.tagline || 'Built for makers who care about the details.')},
    ctaLabel: 'Get early access',
    ctaHref: '/signup',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
  }`,

  FeaturesStagger: (b) => `{
    eyebrow: 'Features',
    headline: 'Designed to feel premium',
    body: 'Every interaction crafted, every transition timed. The little things compound.',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
    features: [
      { icon: '✨', title: 'Crafted motion', body: 'Spring physics on every interaction — no jank, no lag.' },
      { icon: '🎨', title: 'Bold visuals', body: 'Gradient meshes, glass surfaces, layered depth.' },
      { icon: '⚡', title: 'Blazing fast', body: 'Optimized for 60fps on mid-tier hardware.' },
      { icon: '🌗', title: 'Dark by default', body: 'OLED-friendly palette. Less eye strain.' },
      { icon: '🧩', title: 'Composable', body: 'Swap sections, restyle tokens — yours to mould.' },
      { icon: '🔓', title: 'You own it', body: 'Generated source code — no lock-in, no SaaS bill.' },
    ],
  }`,

  FeatureScroll3D: (b) => `{
    eyebrow: 'How it works',
    headline: 'Three moves to ship',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
    segments: [
      { title: '1. Pick your vibe', body: 'Choose from premium templates with 3D, motion, and sections that feel intentional.', color: ${JSON.stringify(b.primary || '#6366f1')} },
      { title: '2. Tune the details', body: 'Brand colour, sections, modules — all controllable. Edit any prop, anywhere.', color: '#ec4899' },
      { title: '3. Own the code', body: 'Export, deploy to Vercel/Docker, customise forever. No platform tax.', color: '#06b6d4' },
    ],
  }`,

  TestimonialsMarqueePremium: (b) => `{
    eyebrow: 'Loved by builders',
    headline: 'Teams shipping faster',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
    quotes: [
      { body: 'Cut our landing-page build time from a week to an afternoon. The 3D hero converts.', authorName: 'Maya P.', authorRole: 'CTO', company: 'Acme' },
      { body: 'The framer motion defaults are tasteful. Felt like hiring a senior designer.', authorName: 'Ravi K.', authorRole: 'Founder', company: 'Linea' },
      { body: 'Shipped a launch page in one evening. The animations sold our preview round.', authorName: 'Sofia L.', authorRole: 'Head of Design', company: 'Glow' },
      { body: 'We were going to hire an agency. This was 2 days of work instead of 6 weeks.', authorName: 'Tom N.', authorRole: 'Marketing', company: 'Pebble' },
      { body: 'Genuinely the best DX for landing pages. The strip pass keeps the bundle tiny.', authorName: 'Aisha R.', authorRole: 'Engineer', company: 'Beam' },
      { body: 'Replaced our Framer subscription. Owning the code matters when you grow.', authorName: 'Jamal K.', authorRole: 'CEO', company: 'Tally' },
    ],
  }`,

  CtaMagnetic: (b) => `{
    headline: 'Ready to ship something beautiful?',
    body: 'Create your account and get started in under a minute.',
    ctaLabel: 'Create account →',
    ctaHref: '/signup',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
  }`,

  // ── Track 2 premium sections ─────────────────────────────────
  PricingPremium: (b) => `{
    eyebrow: 'Pricing',
    headline: 'Built to grow with you',
    body: 'Start free. Upgrade when you outgrow the plan — no lock-in.',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
    tiers: [
      { name: 'Free', price: '$0', cadence: '/mo', tagline: 'For tinkerers',
        features: ['Up to 3 projects', 'Community support', 'Core features'],
        ctaLabel: 'Start free', ctaHref: '/signup' },
      { name: 'Pro', price: '$19', cadence: '/mo', tagline: 'For solo builders',
        features: ['Everything in Free', 'Unlimited projects', 'Email support', 'Custom domain'],
        ctaLabel: 'Start 14-day trial', ctaHref: '/signup', highlight: true },
      { name: 'Team', price: '$49', cadence: '/mo', tagline: 'For growing teams',
        features: ['Everything in Pro', 'SSO + SAML', 'Priority SLA', 'Audit log'],
        ctaLabel: 'Contact sales', ctaHref: '#' },
    ],
  }`,

  PortfolioProjectGrid: (b) => `{
    eyebrow: 'Selected work',
    headline: 'Recent client projects',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
    projects: [
      { title: 'Brand refresh + e-comm rebuild', client: 'Helio Skin', tags: ['brand', 'shopify'], year: '2026', href: '#' },
      { title: 'Internal tools dashboard', client: 'Northwind', tags: ['saas', 'dashboard'], year: '2026', href: '#' },
      { title: 'Marketing site + CMS', client: 'Linea', tags: ['marketing', 'cms'], year: '2025', href: '#' },
      { title: 'Mobile app + onboarding', client: 'Pebble', tags: ['mobile', 'product'], year: '2025', href: '#' },
      { title: 'Design system v2', client: 'Acme', tags: ['design system', 'react'], year: '2025', href: '#' },
      { title: 'Marketplace MVP', client: 'Field', tags: ['marketplace', 'launch'], year: '2024', href: '#' },
    ],
  }`,

  HeroEventCountdown: (b) => {
    // Bake the target date at generate-time. Defaults to 45 days out
    // so the countdown always has something to tick. Users can edit the
    // string in page.tsx (or via Studio prop editor later) to set the
    // real event date.
    const target = new Date(Date.now() + 1000 * 60 * 60 * 24 * 45).toISOString()
    return `{
    eyebrow: 'Save the date',
    headline: ${JSON.stringify(b.name)},
    date: ${JSON.stringify(target)},
    city: 'San Francisco · Hybrid',
    ctaLabel: 'Reserve a seat',
    ctaHref: '/signup',
    accentColor: ${JSON.stringify(b.primary || '#6366f1')},
  }`
  },
}

/** Render JSX for one section. Each is wrapped in <SectionGuard> so
 *  one broken section can't 500 the whole page.
 *
 *  Exported so derive-page-extras can reuse the same default-prop logic
 *  when injecting sections into auth/extra pages. */
export async function renderSection(
  id: string,
  b: Branding,
  sectionsRoot: string | undefined,
): Promise<string> {
  const propFn = SECTION_PROPS[id]
  let propsExpr: string
  if (propFn) {
    propsExpr = propFn(b)
  } else if (sectionsRoot) {
    // Unknown section — synth defaults from section.yaml.
    propsExpr = await synthesiseDefaults(sectionsRoot, id, b)
  } else {
    propsExpr = '{}'
  }
  return `      <SectionGuard name=${JSON.stringify(id)}>
        <${id} {...(${propsExpr} as React.ComponentProps<typeof ${id}>)} />
      </SectionGuard>`
}

export async function derivePage(args: DerivePageArgs): Promise<void> {
  const recipe = args.plan.resolvedRecipe.recipe as {
    sections?: string[]
    branding: Branding
  }
  const sections = recipe.sections
  // No allowlist → leave scaffold's placeholder page.tsx alone (legacy
  // behaviour for non-wizard recipes that haven't opted into composition).
  if (!Array.isArray(sections) || sections.length === 0) return

  const b: Branding = {
    name: recipe.branding.name || 'My App',
    tagline: recipe.branding.tagline,
    primary: recipe.branding.primary,
  }

  const imports = sections
    .map((id) => `import { ${id} } from '@/sections/${id}/${id}'`)
    .join('\n')

  const bodyParts = await Promise.all(
    sections.map((id) => renderSection(id, b, args.sectionsRoot)),
  )
  const body = bodyParts.join('\n')

  const file = `// Generated by b-dash. Edit freely — or drop a replacement
// under overrides/frontend/src/app/page.tsx to preserve it across regens.
'use client'
import * as React from 'react'
${imports}

/**
 * Per-section error boundary. Means one section throwing during render
 * (e.g. missing required prop after a Studio edit) doesn't take down
 * the whole page — the broken section becomes a small placeholder you
 * can identify + fix in Studio's right rail.
 */
class SectionGuard extends React.Component<
  { name: string; children: React.ReactNode },
  { error: Error | null }
> {
  state = { error: null as Error | null }
  static getDerivedStateFromError(error: Error) { return { error } }
  componentDidCatch(error: Error) {
    console.error('[Section ' + this.props.name + ']', error)
  }
  render() {
    if (this.state.error) {
      return (
        <div data-bd-element={'guard:' + this.props.name} style={{
          padding: '24px',
          margin: '16px',
          background: 'rgba(239,68,68,.08)',
          border: '1px dashed rgba(239,68,68,.4)',
          borderRadius: 12,
          color: '#fca5a5',
          fontFamily: 'ui-monospace, Menlo, monospace',
          fontSize: 12,
          textAlign: 'left' as const,
        }}>
          <strong>⚠ Section <code>{this.props.name}</code> failed to render.</strong>
          <p style={{margin: '6px 0 0', opacity: 0.7}}>{this.state.error.message}</p>
          <p style={{margin: '6px 0 0', opacity: 0.5, fontSize: 11}}>
            Edit its props in Studio (right rail) or remove it from this page.
          </p>
        </div>
      )
    }
    return this.props.children
  }
}

export default function HomePage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
${body}
    </main>
  )
}
`

  const appDir = path.join(args.outputDir, 'frontend', 'src', 'app')
  await mkdir(appDir, { recursive: true })
  await writeFile(path.join(appDir, 'page.tsx'), file, 'utf-8')
}
