/**
 * Derive `<output>/backend/app/_adapters.py` — single ``register_adapters()``
 * function calling each module's ``install_default()``.
 *
 * Mirror of ``_subscriptions.py``: lifespan calls ``register_adapters()``
 * once at startup; tests call it from the per-test client fixture (since
 * ASGITransport bypasses real lifespan events). One source of truth for
 * "which gateways are wired"; the operator controls precedence by ordering
 * modules in the recipe (last installer wins on conflicting registries).
 *
 * Detection: any module exposing ``def install_default(`` in
 * ``backend/<stack>/adapters.py`` opts in. No manifest field needed.
 */
import { access, mkdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'
import { pythonPkgName } from './copy-module.js'

export type DeriveAdaptersPyArgs = {
  plan: WirePlan
  modulesRoot: string
  outputDir: string
}

export async function deriveAdaptersPy(
  args: DeriveAdaptersPyArgs,
): Promise<string> {
  const { plan, modulesRoot, outputDir } = args
  const stack = plan.resolvedRecipe.recipe.stack.backend

  // Walk modules in RECIPE INSERTION ORDER (not topological), so the
  // operator's recipe sequence drives "last wins" deterministically.
  // resolvedRecipe.modules is topo-sorted which intermixes alphabetical
  // tie-breaks; the raw recipe.modules array preserves the operator's
  // intent. Look up each module's resolved entry for the manifest.
  const byId = new Map(
    plan.resolvedRecipe.modules.map((m) => [m.id, m]),
  )
  const installers: string[] = []
  for (const recipeMod of plan.resolvedRecipe.recipe.modules) {
    const m = byId.get(recipeMod.id)
    if (!m) continue
    const adaptersPath = path.join(
      modulesRoot,
      m.id,
      'backend',
      stack,
      'adapters.py',
    )
    if (!(await exists(adaptersPath))) continue
    const src = await readFile(adaptersPath, 'utf-8')
    if (!/^def\s+install_default\s*\(/m.test(src)) continue
    installers.push(pythonPkgName(m.id))
  }

  const importLines = installers
    .map(
      (pkg) =>
        `from app.${pkg}.adapters import install_default as _install_${pkg}`,
    )
    .join('\n')
  const callLines =
    installers.length === 0
      ? '    pass  # no adapter modules detected'
      : installers
          .map((pkg) => `    _install_${pkg}()`)
          .join('\n')

  const content = `"""Adapter registration bootstrap.

Generated by b-dash on ${new Date().toISOString()}.
DO NOT EDIT — derived from each module's adapters.py install_default symbol.
Drop replacements under ../overrides/.
"""
${importLines ? importLines + '\n' : ''}

def register_adapters() -> None:
    """Wire each adapter-strategy module's default into its core registry.

    Module-list order in the recipe controls precedence — last call to
    set_payment_adapter (or any other registry) wins. Lifespan + test
    client fixture both call this so behaviour matches in either runtime
    path."""
${callLines}
`

  const dest = path.join(outputDir, 'backend', 'app', '_adapters.py')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}
