/**
 * Derive `<output>/backend/app/_subscriptions.py` from each module's
 * `subscribes:` block.
 *
 * Handler dotted-path (e.g. `app.notifications.handlers.handle_order_placed`)
 * is split into a Python `from <module> import <func>` line and a
 * `subscribe("<event>", <func>)` registration call. Multiple handlers per
 * event are allowed — the in-process bus already fans out (PLAN §13).
 *
 * Modules with no `subscribes:` contribute nothing. If no module subscribes
 * to anything, `register_subscriptions()` is still emitted as a no-op so
 * `main.py` can call it unconditionally.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'

export type DeriveSubscriptionsArgs = {
  plan: WirePlan
  outputDir: string
}

type Subscription = {
  eventId: string
  modulePath: string // python dotted import path (without trailing func)
  funcName: string
}

export async function deriveSubscriptions(
  args: DeriveSubscriptionsArgs,
): Promise<string> {
  const subs: Subscription[] = []
  const skipped: { moduleId: string; eventId: string; reason: string }[] = []

  for (const m of args.plan.resolvedRecipe.modules) {
    const subscribes = m.manifest.subscribes ?? []
    for (const s of subscribes) {
      const handler = (s as { handler?: string }).handler
      if (!handler) {
        skipped.push({
          moduleId: m.id,
          eventId: s.id,
          reason: 'no handler field',
        })
        continue
      }
      // Only Python dotted paths supported. TS handlers (legacy) are skipped
      // — they belong to a future Node-runtime variant of the bus.
      if (handler.endsWith('.ts') || handler.startsWith('./')) {
        skipped.push({
          moduleId: m.id,
          eventId: s.id,
          reason: `handler "${handler}" is not a Python dotted path`,
        })
        continue
      }
      const parts = handler.split('.')
      if (parts.length < 2) {
        skipped.push({
          moduleId: m.id,
          eventId: s.id,
          reason: `handler "${handler}" missing function name`,
        })
        continue
      }
      const funcName = parts[parts.length - 1]
      const modulePath = parts.slice(0, -1).join('.')
      subs.push({ eventId: s.id, modulePath, funcName })
    }
  }

  // Group imports by module path, dedupe func names per module.
  const importsByModule = new Map<string, Set<string>>()
  for (const s of subs) {
    if (!importsByModule.has(s.modulePath)) {
      importsByModule.set(s.modulePath, new Set())
    }
    importsByModule.get(s.modulePath)!.add(s.funcName)
  }

  const importLines = Array.from(importsByModule.entries())
    .sort(([a], [b]) => a.localeCompare(b))
    .map(
      ([mod, names]) =>
        `from ${mod} import ${Array.from(names).sort().join(', ')}`,
    )
    .join('\n')

  const callLines =
    subs.length === 0
      ? '    pass  # no subscriptions registered'
      : subs
          .map((s) => `    subscribe("${s.eventId}", ${s.funcName})`)
          .join('\n')

  const skippedComment =
    skipped.length === 0
      ? ''
      : '\n# Skipped (non-Python handler paths):\n' +
        skipped
          .map((s) => `#   ${s.moduleId} -> ${s.eventId}: ${s.reason}`)
          .join('\n') +
        '\n'

  const content = `"""Bus subscription bootstrap.

Generated by b-dash on ${new Date().toISOString()}.
DO NOT EDIT — derived from each module's \`subscribes:\` block.
Drop replacements under ../overrides/ to preserve them across regenerations.
"""
from app.events_bus.bus import subscribe
${importLines ? '\n' + importLines + '\n' : ''}${skippedComment}

def register_subscriptions() -> None:
    """Wire all module event handlers to the in-process bus (PLAN §13)."""
${callLines}
`

  const dest = path.join(args.outputDir, 'backend', 'app', '_subscriptions.py')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}
