/**
 * Per-module models.py emitter for the Django stack.
 *
 * Convention: if a module ships a hand-written ``backend/django/models.py``
 * (e.g. auth-core's custom AbstractBaseUser), we leave it alone. Otherwise
 * we translate the module's ``schema.prisma`` into a Django models module
 * via ``prisma.ts``.
 *
 * Plus: every module dir under ``<out>/backend/<pkg>/`` gets an ``apps.py``
 * fallback (with ``label = "<pkg>"`` + ``name = "<pkg>"``) so Django can
 * register the app even if the module didn't author one. Same for
 * ``__init__.py`` — Django needs the dir to be a Python package.
 */
import { access, mkdir, readFile, readdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'
import {
  buildModelRegistry,
  emitDjangoModels,
  pairAcrossFiles,
  parsePrismaSchema,
  type ModelDef,
} from '../db/prisma.js'
import { pythonPkgName } from './copy-module.js'

export async function deriveDjangoModels(args: {
  plan: WirePlan
  modulesRoot: string
  outputDir: string
}): Promise<{ generated: string[]; skipped: string[] }> {
  const generated: string[] = []
  const skipped: string[] = []

  // Pass 1: parse every module's prisma schema (or hand-written models.py
  // we can't read into the registry — those modules are skipped) so the
  // FK emitter can resolve cross-module targets to ``<app>.Model``.
  const perModule: {
    moduleId: string
    pythonPkg: string
    models: ModelDef[]
  }[] = []
  for (const m of args.plan.resolvedRecipe.modules) {
    const prisma = path.join(args.modulesRoot, m.id, 'schema.prisma')
    if (!(await exists(prisma))) continue
    const src = await readFile(prisma, 'utf-8')
    perModule.push({
      moduleId: m.id,
      pythonPkg: pythonPkgName(m.id),
      models: parsePrismaSchema(src),
    })
  }
  // Cross-file relation pairing — within-file pairs already wired by the
  // parser; this matches forwards in module A with reverses in module B
  // before any model.py emit consumes the relations array.
  pairAcrossFiles(perModule.flatMap((p) => p.models))

  const registry = buildModelRegistry(perModule)
  // auth-core's User model is hand-written (custom AbstractBaseUser) so
  // its schema.prisma maps it but the file isn't always shipped with a
  // ``users`` @@map matching the runtime table; ensure the registry has
  // the entry expected by downstream FK emitters.
  if (!registry.has('User')) {
    registry.set('User', {
      tableName: 'users',
      sourceModuleId: 'auth-core',
      pythonPkg: 'auth_core',
    })
  }

  // Pass 2: emit per-module models.py + apps.py + migrations stub.
  const parsedByModule = new Map(
    perModule.map((p) => [p.moduleId, p.models]),
  )
  for (const m of args.plan.resolvedRecipe.modules) {
    const pkg = pythonPkgName(m.id)
    const moduleRoot = path.join(args.modulesRoot, m.id)
    const appDir = path.join(args.outputDir, 'backend', pkg)

    // Ensure the Django app dir exists as a Python package even if the
    // module shipped no per-stack files for django (it might be a behaviour
    // module like events-bus). Also stub a migrations/ package so Django's
    // ``makemigrations`` discovers the app — without this it silently skips.
    await mkdir(appDir, { recursive: true })
    await mkdir(path.join(appDir, 'migrations'), { recursive: true })
    await ensureFile(path.join(appDir, '__init__.py'), '')
    await ensureFile(path.join(appDir, 'migrations', '__init__.py'), '')
    await ensureFile(
      path.join(appDir, 'apps.py'),
      defaultAppsPy(pkg, m.manifest.displayName ?? m.id),
    )

    const handWritten = path.join(moduleRoot, 'backend', 'django', 'models.py')
    const out = path.join(appDir, 'models.py')

    if (await exists(handWritten)) {
      skipped.push(m.id)
      continue
    }
    const models = parsedByModule.get(m.id)
    if (!models || models.length === 0) {
      skipped.push(m.id)
      continue
    }
    const py = emitDjangoModels(models, registry)
    await writeFile(out, py, 'utf-8')
    generated.push(m.id)
  }

  return { generated, skipped }
}

function defaultAppsPy(pkg: string, displayName: string): string {
  return `"""Django AppConfig for ${pkg} — generated by b-dash."""
from django.apps import AppConfig


class ${pascal(pkg)}Config(AppConfig):
    default_auto_field = "django.db.models.BigAutoField"
    name = "${pkg}"
    label = "${pkg}"
    verbose_name = ${JSON.stringify(displayName)}
`
}

function pascal(snake: string): string {
  return snake
    .split('_')
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('')
}

async function ensureFile(p: string, contents: string): Promise<void> {
  if (await exists(p)) return
  await writeFile(p, contents, 'utf-8')
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}

// satisfy unused-readdir linter; reserved for future "delete stale" pass.
void readdir
