/**
 * Derive `<output>/backend/app/main.py` from the wire plan.
 *
 * For each module with `backend/<stack>/router.py`, emit one or more
 * `app.include_router(...)` lines based on the module's `backend_routers`
 * manifest field. Default (when omitted): one entry pointing at the module's
 * `router` symbol mounted at `/api/<id>`.
 *
 * For each module with `backend/<stack>/model.py`, import inside lifespan so
 * SQLAlchemy registers tables before init_db() runs.
 *
 * For each module exporting an `install_default()` from `<pkg>/adapters.py`,
 * call it in lifespan startup so adapter-strategy modules (payment-fake,
 * payment-stripe, future notifications-resend, ...) register themselves
 * with their respective core registries before the app accepts traffic.
 * Module load order in the recipe decides which gateway wins on conflicts
 * (last call to set_payment_adapter wins).
 */
import { access, readFile, writeFile, mkdir } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'
import { pythonPkgName } from './copy-module.js'

export type DeriveMainPyArgs = {
  plan: WirePlan
  modulesRoot: string
  outputDir: string
}

type RouterEntry = {
  exportName: string
  prefix: string
  tag: string
}

export async function deriveMainPy(args: DeriveMainPyArgs): Promise<string> {
  const { plan, modulesRoot, outputDir } = args
  const stack = plan.resolvedRecipe.recipe.stack.backend

  const importLinesParts: string[] = []
  const includeLinesParts: string[] = []
  const withModel: string[] = []

  for (const m of plan.resolvedRecipe.modules) {
    const moduleRoot = path.join(modulesRoot, m.id)

    const pkg = pythonPkgName(m.id)

    if (await exists(path.join(moduleRoot, 'backend', stack, 'router.py'))) {
      const routers: RouterEntry[] =
        m.manifest.backend_routers && m.manifest.backend_routers.length > 0
          ? m.manifest.backend_routers.map((r) => ({
              exportName: r.exportName,
              prefix: r.prefix,
              tag: r.tag ?? m.id,
            }))
          : [{ exportName: 'router', prefix: `/api/${m.id}`, tag: m.id }]

      for (const r of routers) {
        const localName = `${pkg}_${r.exportName}`
        importLinesParts.push(
          `from app.${pkg}.router import ${r.exportName} as ${localName}`,
        )
        includeLinesParts.push(
          `app.include_router(${localName}, prefix="${r.prefix}", tags=["${r.tag}"])`,
        )
      }
    }

    if (await exists(path.join(moduleRoot, 'backend', stack, 'model.py'))) {
      withModel.push(pkg)
    }
  }

  const importLines = importLinesParts.join('\n')
  const includeLines = includeLinesParts.join('\n')

  const modelImportLines = withModel
    .map((id) => `    import app.${id}.model  # noqa: F401`)
    .join('\n')

  const appName = plan.resolvedRecipe.recipe.branding.name.replace(/"/g, '\\"')

  const content = `"""FastAPI entry point.

Generated by b-dash on ${new Date().toISOString()}.
DO NOT EDIT — run \`b-dash generate\` to regenerate.
Drop replacements under ../overrides/ to preserve them across regenerations.
"""
from contextlib import asynccontextmanager
from typing import AsyncGenerator

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from loguru import logger

from app.config import settings
from app.database import close_db, init_db
from app.middleware.error_handler import register_error_handlers
from app._adapters import register_adapters
from app._subscriptions import register_subscriptions
${importLines ? '\n' + importLines + '\n' : ''}

@asynccontextmanager
async def lifespan(_: FastAPI) -> AsyncGenerator[None, None]:
    logger.info("Starting backend")
${modelImportLines || '    pass  # no module models registered'}
    register_adapters()
    register_subscriptions()
    await init_db()
    yield
    logger.info("Shutting down backend")
    await close_db()


app = FastAPI(
    title="${appName}",
    version="0.1.0",
    lifespan=lifespan,
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=settings.cors_origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

register_error_handlers(app)
${includeLines ? '\n' + includeLines + '\n' : ''}

@app.get("/healthz", tags=["meta"])
async def healthz() -> dict[str, str]:
    return {"status": "ok"}
`

  const dest = path.join(outputDir, 'backend', 'app', 'main.py')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}
