/**
 * Compile a theme's tokens.json into <output>/frontend/src/app/globals.css
 * with CSS custom properties.
 *
 * Tailwind's `colors.primary = 'hsl(var(--primary))'` indirection means we
 * emit HSL triples (without the `hsl(...)` wrapper) so Tailwind can compose
 * with `/<opacity>` modifiers.
 *
 * MVP: emit a curated subset (background, foreground, primary, secondary,
 * destructive, muted, accent, card, border, input, ring, radius). Full token
 * → Tailwind config generation lands in Chunk C3.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { LoadedTheme } from '../types.js'

const HSL_FALLBACKS = {
  background: '0 0% 100%',
  foreground: '222.2 84% 4.9%',
  card: '0 0% 100%',
  'card-foreground': '222.2 84% 4.9%',
  primary: '222.2 47.4% 11.2%',
  'primary-foreground': '210 40% 98%',
  secondary: '210 40% 96.1%',
  'secondary-foreground': '222.2 47.4% 11.2%',
  muted: '210 40% 96.1%',
  'muted-foreground': '215.4 16.3% 46.9%',
  accent: '210 40% 96.1%',
  'accent-foreground': '222.2 47.4% 11.2%',
  destructive: '0 84.2% 60.2%',
  'destructive-foreground': '210 40% 98%',
  border: '214.3 31.8% 91.4%',
  input: '214.3 31.8% 91.4%',
  ring: '222.2 84% 4.9%',
} as const

const HSL_DARK_FALLBACKS = {
  background: '222.2 84% 4.9%',
  foreground: '210 40% 98%',
  card: '222.2 84% 4.9%',
  'card-foreground': '210 40% 98%',
  primary: '210 40% 98%',
  'primary-foreground': '222.2 47.4% 11.2%',
  secondary: '217.2 32.6% 17.5%',
  'secondary-foreground': '210 40% 98%',
  muted: '217.2 32.6% 17.5%',
  'muted-foreground': '215 20.2% 65.1%',
  accent: '217.2 32.6% 17.5%',
  'accent-foreground': '210 40% 98%',
  destructive: '0 62.8% 30.6%',
  'destructive-foreground': '210 40% 98%',
  border: '217.2 32.6% 17.5%',
  input: '217.2 32.6% 17.5%',
  ring: '212.7 26.8% 83.9%',
} as const

export async function deriveGlobalsCss(args: {
  theme: LoadedTheme
  outputDir: string
}): Promise<string> {
  const { theme, outputDir } = args

  // For MVP: ignore the rich tokens.json and emit shadcn-style HSL fallbacks.
  // Theme's `category` could later select a different palette per theme.
  // (Real token → CSS-var mapping is Chunk C3 work.)
  const radius = theme.tokens.radius?.lg ?? '0.5rem'

  const lightVars = Object.entries(HSL_FALLBACKS)
    .map(([k, v]) => `    --${k}: ${v};`)
    .join('\n')

  const darkVars = theme.darkTokens || true
    ? Object.entries(HSL_DARK_FALLBACKS)
        .map(([k, v]) => `    --${k}: ${v};`)
        .join('\n')
    : ''

  const content = `/* Generated by b-dash from theme: ${theme.pack}. DO NOT EDIT. */
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
  :root {
${lightVars}
    --radius: ${radius};
  }

  .dark {
${darkVars}
  }
}

@layer base {
  * {
    @apply border-border;
  }
  body {
    @apply bg-background text-foreground;
  }
}
`

  const dest = path.join(outputDir, 'frontend', 'src', 'app', 'globals.css')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}
