/**
 * Sprint 21 — emit a Next.js middleware.ts that gates pages per
 * recipe.pageGuards. Runs at the EDGE on every request matching the
 * configured paths. Redirects to /login when the auth cookie is missing
 * (or to /403 when role-gated and user lacks role).
 *
 * For Sprint 21 V1 the role check is rudimentary — it reads the role
 * from a "authRole" cookie set by the auth flow. Real apps will swap
 * this for a JWT decode or server-side session lookup; this is a starter
 * that works for the common case (cookie-based auth).
 *
 * No-op when pageGuards is missing/empty.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'

export type DeriveMiddlewareArgs = {
  plan: WirePlan
  outputDir: string
}

export async function deriveMiddleware(args: DeriveMiddlewareArgs): Promise<{ written: boolean }> {
  const recipe = args.plan.resolvedRecipe.recipe as { pageGuards?: Record<string, string> }
  const guards = recipe.pageGuards ?? {}
  if (Object.keys(guards).length === 0) return { written: false }

  // Build matcher entries — Next middleware uses pathname patterns.
  const entries: Array<{ pageId: string; route: string; guard: string }> = []
  for (const [pageId, guard] of Object.entries(guards)) {
    const route = pageId === 'home' ? '/' : `/${pageId}`
    entries.push({ pageId, route, guard })
  }
  // Sort longest first so /dashboard/admin matches before /dashboard
  entries.sort((a, b) => b.route.length - a.route.length)

  const guardJs = entries
    .map((e) => {
      const role = e.guard.startsWith('role:') ? JSON.stringify(e.guard.slice(5)) : null
      const cond = role
        ? `pathname === ${JSON.stringify(e.route)} || pathname.startsWith(${JSON.stringify(e.route + '/')})`
        : `pathname === ${JSON.stringify(e.route)} || pathname.startsWith(${JSON.stringify(e.route + '/')})`
      const action = role
        ? `if (!token) return NextResponse.redirect(new URL('/login', req.url))
        if (role !== ${role}) return NextResponse.redirect(new URL('/403', req.url))`
        : `if (!token) return NextResponse.redirect(new URL('/login', req.url))`
      return `      if (${cond}) {
        ${action}
        return NextResponse.next()
      }`
    })
    .join('\n')

  const matcher = JSON.stringify(
    Array.from(new Set(entries.flatMap((e) => [
      e.route === '/' ? '/' : e.route,
      e.route === '/' ? '/' : `${e.route}/:path*`,
    ]))),
  )

  const content = `// Generated by b-dash (Sprint 21 — page guards)
import { NextResponse, type NextRequest } from 'next/server'

/**
 * Cookie-based access control. Reads:
 *   - authToken  (set on login; any value = "logged in" for V1)
 *   - authRole   (optional; used for role: guards)
 *
 * To upgrade: swap the cookie reads for a JWT verify + role-claim
 * lookup. The shape (redirect to /login on missing auth, /403 on
 * missing role) stays the same.
 */
export function middleware(req: NextRequest) {
  const token = req.cookies.get('authToken')?.value
  const role  = req.cookies.get('authRole')?.value ?? null
  const { pathname } = req.nextUrl
${guardJs}
  return NextResponse.next()
}

export const config = {
  matcher: ${matcher},
}
`

  const dest = path.join(args.outputDir, 'frontend', 'src', 'middleware.ts')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return { written: true }
}
