/**
 * Derive `<output>/frontend/tailwind.config.ts` by extending the scaffold's
 * static config with theme-token-derived color scales, fontFamily, spacing,
 * borderRadius, and shadows.
 *
 * Strategy: keep the shadcn-style CSS-var indirection for semantic names
 * (`bg-primary`, `bg-card`) so swapping themes at runtime via :root vars
 * still works. ALSO inject the full numeric scales straight from
 * `tokens.json` (e.g. `bg-primary-500`) so designers can pick any shade.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { LoadedTheme } from '../types.js'

export type DeriveTailwindConfigArgs = {
  theme: LoadedTheme
  outputDir: string
}

export async function deriveTailwindConfig(
  args: DeriveTailwindConfigArgs,
): Promise<string> {
  const { theme, outputDir } = args
  const tokens = theme.tokens

  const colors = (tokens as { colors?: Record<string, unknown> }).colors ?? {}
  const numericScales = extractNumericScales(colors)
  const semanticColors = extractSemanticColors(colors)

  const fontFamily = extractFontFamily(tokens)
  const spacing = (tokens as { spacing?: Record<string, string> }).spacing ?? {}
  const radius = (tokens as { radius?: Record<string, string> }).radius ?? {}
  const shadows = (tokens as { shadows?: Record<string, string> }).shadows ?? {}

  const content = `import type { Config } from 'tailwindcss'

/**
 * Generated by b-dash from theme: ${theme.pack}.
 * DO NOT EDIT — re-run \`b-dash generate\` to regenerate.
 *
 * Numeric scales (primary-50..950, etc.) come from the theme's tokens.json.
 * Semantic names (bg-primary, bg-card) flow through CSS vars in globals.css
 * so dark mode + per-tenant overrides can re-target them at runtime.
 */
const config: Config = {
  content: ['./src/components/**/*.{ts,tsx}', './src/app/**/*.{ts,tsx}'],
  darkMode: ['class'],
  theme: {
    extend: {
      colors: ${stringifyJs(
        {
          // CSS-var-driven semantic palette (shadcn style)
          border: 'hsl(var(--border))',
          input: 'hsl(var(--input))',
          ring: 'hsl(var(--ring))',
          background: 'hsl(var(--background))',
          foreground: 'hsl(var(--foreground))',
          primary: {
            DEFAULT: 'hsl(var(--primary))',
            foreground: 'hsl(var(--primary-foreground))',
            ...(numericScales.primary ?? {}),
          },
          secondary: {
            DEFAULT: 'hsl(var(--secondary))',
            foreground: 'hsl(var(--secondary-foreground))',
            ...(numericScales.secondary ?? {}),
          },
          destructive: {
            DEFAULT: 'hsl(var(--destructive))',
            foreground: 'hsl(var(--destructive-foreground))',
          },
          muted: {
            DEFAULT: 'hsl(var(--muted))',
            foreground: 'hsl(var(--muted-foreground))',
          },
          accent: {
            DEFAULT: 'hsl(var(--accent))',
            foreground: 'hsl(var(--accent-foreground))',
            ...(numericScales.accent ?? {}),
          },
          card: {
            DEFAULT: 'hsl(var(--card))',
            foreground: 'hsl(var(--card-foreground))',
          },
          // Extra numeric scales straight from tokens.json
          ...(numericScales.neutral
            ? { neutral: numericScales.neutral }
            : {}),
          // Semantic groups (success/warning/error/info) flat-emitted
          ...semanticColors,
        },
        4,
      )},
      ${
        Object.keys(fontFamily).length > 0
          ? `fontFamily: ${stringifyJs(fontFamily, 4)},\n      `
          : ''
      }${
        Object.keys(spacing).length > 0
          ? `spacing: ${stringifyJs(spacing, 4)},\n      `
          : ''
      }borderRadius: ${stringifyJs(
        // Token literal values (lg/md/sm) override the CSS-var fallback so
        // designers get exactly what tokens.json declares. Other named
        // radii (xl, 2xl, full, ...) come straight from tokens.
        Object.keys(radius).length > 0
          ? radius
          : {
              lg: 'var(--radius)',
              md: 'calc(var(--radius) - 2px)',
              sm: 'calc(var(--radius) - 4px)',
            },
        4,
      )},
      ${
        Object.keys(shadows).length > 0
          ? `boxShadow: ${stringifyJs(shadows, 4)},\n      `
          : ''
      }
    },
  },
  plugins: [],
}

export default config
`

  const dest = path.join(outputDir, 'frontend', 'tailwind.config.ts')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}

/**
 * Pull color groups whose values look like numeric Tailwind scales
 * ({"50": "#...", "100": "#...", ...}) into a `{[group]: {50: ..., ...}}` map.
 */
function extractNumericScales(
  colors: Record<string, unknown>,
): Record<string, Record<string, string>> {
  const out: Record<string, Record<string, string>> = {}
  for (const [name, val] of Object.entries(colors)) {
    if (!val || typeof val !== 'object' || Array.isArray(val)) continue
    const entries = Object.entries(val as Record<string, unknown>)
    const numeric = entries.filter(([k, v]) => /^\d+$/.test(k) && typeof v === 'string')
    if (numeric.length >= 5) {
      out[name] = Object.fromEntries(numeric as [string, string][])
    }
  }
  return out
}

/**
 * Flatten semantic color groups (e.g. `semantic.success.{bg,fg,border}`) into
 * `success-bg`, `success-fg`, `success-border` so they're addressable as
 * `bg-success-bg`, `text-success-fg`, etc.
 */
function extractSemanticColors(
  colors: Record<string, unknown>,
): Record<string, string> {
  const out: Record<string, string> = {}
  const semantic = (colors as { semantic?: Record<string, unknown> }).semantic
  if (!semantic || typeof semantic !== 'object') return out
  for (const [groupName, group] of Object.entries(semantic)) {
    if (!group || typeof group !== 'object') continue
    for (const [k, v] of Object.entries(group as Record<string, unknown>)) {
      if (typeof v === 'string') out[`${groupName}-${k}`] = v
    }
  }
  return out
}

function extractFontFamily(tokens: unknown): Record<string, string[]> {
  const t = tokens as {
    typography?: { fontPair?: string; families?: Record<string, string[]> }
  }
  if (t.typography?.families) return t.typography.families
  // Conservative default: map fontPair "geist-jetbrains-mono" -> sans + mono.
  if (t.typography?.fontPair === 'geist-jetbrains-mono') {
    return {
      sans: ['Geist', 'system-ui', 'sans-serif'],
      mono: ['JetBrains Mono', 'ui-monospace', 'monospace'],
    }
  }
  return {}
}

/**
 * Pretty-print a JS literal (handles nested objects + string values).
 * Not JSON: object keys are unquoted when valid identifiers, and string
 * values stay single-quoted to fit the surrounding TS file style.
 */
function stringifyJs(value: unknown, indent: number): string {
  return formatJs(value, indent, 0)
}

function formatJs(value: unknown, baseIndent: number, depth: number): string {
  if (value === null || value === undefined) return 'undefined'
  if (typeof value === 'string') return JSON.stringify(value).replace(/^"|"$/g, "'")
  if (typeof value === 'number' || typeof value === 'boolean') return String(value)
  if (Array.isArray(value)) {
    const inner = value
      .map((v) => formatJs(v, baseIndent, depth + 1))
      .join(', ')
    return `[${inner}]`
  }
  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>).filter(
      ([, v]) => v !== undefined,
    )
    if (entries.length === 0) return '{}'
    const pad = ' '.repeat(baseIndent * (depth + 1) + 2)
    const closePad = ' '.repeat(baseIndent * depth + 2)
    const lines = entries.map(([k, v]) => {
      // Bare identifier when valid; otherwise single-quoted (matches the
      // single-quoted style we use for string values).
      const key = /^[A-Za-z_$][\w$]*$/.test(k) ? k : `'${k.replace(/'/g, "\\'")}'`
      return `${pad}${key}: ${formatJs(v, baseIndent, depth + 1)},`
    })
    return `{\n${lines.join('\n')}\n${closePad}}`
  }
  return String(value)
}
