/**
 * Sprint 12b — emit a minimal page.tsx for every slug in
 * `recipe.blankPages`. Pairs with derive-page-extras: blank pages give
 * the user an empty canvas to drop sections onto via pageExtras.
 *
 * Why "blank" instead of "use a template"?
 *   - Templates already exist via recipe.extraPages (pricing/about/etc.).
 *   - Custom routes (e.g. /our-team, /careers, /case-study-x) are too
 *     varied to fit any one template — start empty, let the user
 *     compose with sections + element-level edits.
 *
 * The emitted file has:
 *   - 'use client' directive (so the bridge can attach)
 *   - <main> wrapper with a tiny prompt explaining the empty state
 *   - data-bd-element attrs (injected by deriveElementIds in the next
 *     pipeline step) so the bridge can address every element
 *
 * Runs after deriveExtraPages + before deriveElementIds.
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'

export type DeriveBlankPagesArgs = {
  plan: WirePlan
  outputDir: string
}

type Branding = { name?: string; tagline?: string; primary?: string }

export async function deriveBlankPages(args: DeriveBlankPagesArgs): Promise<{ count: number }> {
  const recipe = args.plan.resolvedRecipe.recipe as {
    blankPages?: string[]
    branding?: Branding
  }
  const slugs = recipe.blankPages
  if (!Array.isArray(slugs) || slugs.length === 0) return { count: 0 }

  const appDir = path.join(args.outputDir, 'frontend', 'src', 'app')
  const brand = recipe.branding?.name || 'App'
  let count = 0

  for (const slug of slugs) {
    if (!/^[a-z][a-z0-9-]{0,40}$/.test(slug)) continue
    const dir = path.join(appDir, slug)
    await mkdir(dir, { recursive: true })
    const pageFile = path.join(dir, 'page.tsx')
    // Idempotent: don't overwrite if the file is already user-edited
    // (it ALWAYS exists if the wirer ran before — overlay step puts
    // any user overrides on top). For simplicity, write a fresh stub
    // every time; user edits live in overrides/<rel> + apply on top.
    await writeFile(pageFile, buildBlankPage(slug, brand), 'utf-8')
    count++
  }

  return { count }
}

function buildBlankPage(slug: string, brand: string): string {
  // Title-case the slug for the placeholder heading
  const title = slug
    .split('-')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join(' ')
  return `// Generated by b-dash (blank page — composeable). Edit freely
// or drop a replacement under overrides/frontend/src/app/${slug}/page.tsx
// to preserve it across regens. Add sections via recipe.pageExtras["${slug}"].
'use client'

export default function ${pascalCase(slug)}Page() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <section className="mx-auto max-w-3xl px-6 py-20 text-center">
        <p className="mb-3 text-xs font-semibold uppercase tracking-[0.2em] text-muted-foreground">
          ${title}
        </p>
        <h1 className="mb-4 text-4xl font-bold tracking-tight md:text-5xl">
          ${title}
        </h1>
        <p className="mx-auto max-w-xl text-lg text-muted-foreground">
          Welcome to /${slug}. Click any element to edit, or use Studio's
          left palette to add sections. Replace this placeholder via the
          Code tab when you have your final layout.
        </p>
      </section>
    </main>
  )
}
`
}

function pascalCase(s: string): string {
  return s
    .split(/[-_\s]+/)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
}
