/**
 * Compose a real homepage from `recipe.sections`.
 *
 * Plan §19.1 step 8 — "APPLY PAGES". Without this step the generated
 * frontend ships only the scaffold's `Hello.` placeholder and the
 * copied section components sit orphaned in `src/sections/`.
 *
 * This step generates `<out>/frontend/src/app/page.tsx` that:
 *   - Imports each section component listed in `recipe.sections`
 *   - Renders them top-to-bottom with realistic demo props
 *   - Threads `recipe.branding` (name + tagline + primary colour) into
 *     the hero / header / footer so the page actually says the user's
 *     app name instead of "Generated by b-dash."
 *
 * If `recipe.sections` is absent or empty, the scaffold's placeholder
 * `page.tsx` stays untouched (back-compat for non-wizard recipes).
 */
import { mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'

type Branding = {
  name: string
  tagline?: string
  primary?: string
}

export type DerivePageArgs = {
  plan: WirePlan
  outputDir: string
}

/**
 * Per-section demo props. Keyed by section id. Each value is a JS
 * expression rendered into the JSX as `{...obj}` so we can pass arrays
 * of objects safely (no string-escaping headaches).
 *
 * Hero / header / footer entries reference `brandName` / `tagline` which
 * are injected as locals in the generated page.
 */
const SECTION_PROPS: Record<string, (b: Branding) => string> = {
  HeaderMinimal: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    brandHref: '/',
    links: [
      { label: 'Features', href: '#features' },
      { label: 'Pricing', href: '#pricing' },
      { label: 'FAQ', href: '#faq' },
    ],
    ctaLabel: 'Get started',
    ctaHref: '#cta',
  }`,
  HeaderMega: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    columns: [
      { title: 'Product', links: [{ label: 'Features', href: '#features' }] },
      { title: 'Resources', links: [{ label: 'Docs', href: '/docs' }] },
    ],
    ctaLabel: 'Sign up',
    ctaHref: '#cta',
  }`,
  TopNav: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    links: [
      { label: 'Home', href: '/' },
      { label: 'About', href: '/about' },
    ],
  }`,

  HeroCentered: (b) => `{
    eyebrow: 'Welcome',
    headline: ${JSON.stringify(b.name)},
    body: ${JSON.stringify(b.tagline || 'A modern app built with B-Dash.')},
    ctaLabel: 'Get started',
    ctaHref: '#cta',
    secondaryLabel: 'Learn more',
    secondaryHref: '#features',
  }`,

  FeatureGrid3Col: () => `{
    eyebrow: 'Features',
    headline: 'Everything you need',
    body: 'A focused toolkit that gets out of your way.',
    features: [
      { icon: '⚡', title: 'Fast', body: 'Boots instantly. No bloat.' },
      { icon: '🔒', title: 'Secure', body: 'Sensible defaults baked in.' },
      { icon: '🎨', title: 'Yours', body: 'Own the code. Deploy anywhere.' },
    ],
  }`,

  CompanyWall: () => `{
    heading: 'Loved by teams',
    cells: [
      { logoUrl: '', companyName: 'Acme', quote: 'Game changer.', authorName: 'Ada', authorRole: 'CTO' },
      { logoUrl: '', companyName: 'Globex', quote: 'Shipped in a week.', authorName: 'Ben', authorRole: 'PM' },
      { logoUrl: '', companyName: 'Initech', quote: 'Just works.', authorName: 'Carla', authorRole: 'Eng' },
    ],
  }`,

  PricingCompare: () => `{
    heading: 'Simple pricing',
    columns: [
      { name: 'Free', tagline: 'Try it out', price: '$0', cadence: '/mo',
        ctaLabel: 'Start free', ctaHref: '#', bullets: ['Core features', 'Community support'] },
      { name: 'Pro', tagline: 'For growing teams', price: '$19', cadence: '/mo',
        ctaLabel: 'Start trial', ctaHref: '#', bullets: ['Everything in Free', 'Email support', 'Custom domains'],
        highlight: true },
      { name: 'Team', tagline: 'For scale', price: '$49', cadence: '/mo',
        ctaLabel: 'Contact sales', ctaHref: '#', bullets: ['Everything in Pro', 'SSO', 'Priority SLA'] },
    ],
  }`,

  FaqAccordion: () => `{
    eyebrow: 'FAQ',
    headline: 'Frequently asked questions',
    items: [
      { question: 'Is this free?', answer: 'A free tier is available. Paid plans start at $19/mo.' },
      { question: 'Do I own the code?', answer: 'Yes — the entire codebase is yours to deploy anywhere.' },
      { question: 'Can I customize it?', answer: 'Yes — edit any file, or use overrides/ to preserve changes across regens.' },
    ],
  }`,

  CtaCentered: () => `{
    headline: 'Ready to ship?',
    body: 'Build a working app in minutes — not months.',
    ctaLabel: 'Get started',
    ctaHref: '#',
  }`,

  FooterColumns: (b) => `{
    brandName: ${JSON.stringify(b.name)},
    tagline: ${JSON.stringify(b.tagline || '')},
    columns: [
      { title: 'Product', links: [
        { label: 'Features', href: '#features' },
        { label: 'Pricing', href: '#pricing' },
      ] },
      { title: 'Company', links: [
        { label: 'About', href: '/about' },
        { label: 'Contact', href: '/contact' },
      ] },
      { title: 'Legal', links: [
        { label: 'Privacy', href: '/privacy' },
        { label: 'Terms', href: '/terms' },
      ] },
    ],
    legal: '© 2026 ' + ${JSON.stringify(b.name)},
  }`,

  NewsletterSignup: () => `{
    headline: 'Stay in the loop',
    body: 'One short update per month. No spam, ever.',
    placeholder: 'you@example.com',
    ctaLabel: 'Subscribe',
    actionUrl: '/api/newsletter/subscribe',
  }`,

  BlogHeroFeatured: () => `{
    eyebrow: 'Featured',
    headline: 'Welcome to the blog',
    excerpt: 'Long-form posts on what we are building.',
    href: '/posts/welcome',
    authorName: 'The team',
    publishedAt: 'May 31, 2026',
  }`,

  BlogArchive: () => `{
    heading: 'Archive',
    years: [
      { year: '2026', months: [
        { label: 'May', href: '/blog/2026/05', count: 4 },
        { label: 'April', href: '/blog/2026/04', count: 6 },
      ] },
    ],
  }`,

  BlogCardHorizontal: () => `{
    title: 'Welcome to the blog',
    excerpt: 'Our very first post.',
    href: '/posts/welcome',
    authorName: 'The team',
    publishedAt: 'May 31, 2026',
    imageUrl: '',
  }`,

  CardCarousel: () => `{
    heading: 'Selected work',
    cards: [
      { title: 'Project Alpha', body: 'A polished thing.', imageUrl: '', href: '#' },
      { title: 'Project Beta',  body: 'Another polished thing.', imageUrl: '', href: '#' },
      { title: 'Project Gamma', body: 'Yet another.', imageUrl: '', href: '#' },
    ],
  }`,

  ProductGallery: () => `{
    images: [
      { url: '', alt: 'Product front' },
      { url: '', alt: 'Product side' },
      { url: '', alt: 'Product back' },
    ],
  }`,
}

/** Render JSX for one section. Provides sane props or empty object. */
function renderSection(id: string, b: Branding): string {
  const propFn = SECTION_PROPS[id]
  const propsExpr = propFn ? propFn(b) : '{}'
  return `      <${id} {...(${propsExpr} as React.ComponentProps<typeof ${id}>)} />`
}

export async function derivePage(args: DerivePageArgs): Promise<void> {
  const recipe = args.plan.resolvedRecipe.recipe as {
    sections?: string[]
    branding: Branding
  }
  const sections = recipe.sections
  // No allowlist → leave scaffold's placeholder page.tsx alone (legacy
  // behaviour for non-wizard recipes that haven't opted into composition).
  if (!Array.isArray(sections) || sections.length === 0) return

  const b: Branding = {
    name: recipe.branding.name || 'My App',
    tagline: recipe.branding.tagline,
    primary: recipe.branding.primary,
  }

  const imports = sections
    .map((id) => `import { ${id} } from '@/sections/${id}/${id}'`)
    .join('\n')

  const body = sections.map((id) => renderSection(id, b)).join('\n')

  const file = `// Generated by b-dash. Edit freely — or drop a replacement
// under overrides/frontend/src/app/page.tsx to preserve it across regens.
import * as React from 'react'
${imports}

export default function HomePage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
${body}
    </main>
  )
}
`

  const appDir = path.join(args.outputDir, 'frontend', 'src', 'app')
  await mkdir(appDir, { recursive: true })
  await writeFile(path.join(appDir, 'page.tsx'), file, 'utf-8')
}
