/**
 * Derive `<output>/backend/config/urls.py` for Django backends.
 *
 * For each module that ships ``backend/django/urls.py``, mount it at
 * ``/api/<id>/`` (kebab → snake conversion mirrors copy-module's pkg naming).
 * Always keep the scaffold's ``/healthz`` ping.
 */
import { access, mkdir, writeFile } from 'node:fs/promises'
import path from 'node:path'
import type { WirePlan } from '../types.js'
import { pythonPkgName } from './copy-module.js'

export type DeriveDjangoUrlsArgs = {
  plan: WirePlan
  modulesRoot: string
  outputDir: string
}

export async function deriveDjangoUrls(
  args: DeriveDjangoUrlsArgs,
): Promise<string> {
  const { plan, modulesRoot, outputDir } = args
  const includes: string[] = []

  for (const m of plan.resolvedRecipe.modules) {
    const urlsPath = path.join(modulesRoot, m.id, 'backend', 'django', 'urls.py')
    if (!(await exists(urlsPath))) continue
    const pkg = pythonPkgName(m.id)
    // auth-* modules conventionally cluster under /api/auth/ instead of
    // /api/auth_core/ etc. Special-case the prefix when the manifest declared
    // backend_routers — reuse the first one's prefix verbatim.
    const declared = m.manifest.backend_routers?.[0]?.prefix
    const prefix = declared ? declared.replace(/^\//, '').replace(/\/$/, '') : `api/${m.id}`
    includes.push(
      `    path("${prefix}/", include("${pkg}.urls", namespace="${pkg}")),`,
    )
  }

  const content = `"""Root URL config — generated by b-dash on ${new Date().toISOString()}.

DO NOT EDIT — re-run \`b-dash generate\` to regenerate.
Drop replacements under ../overrides/ to preserve them across regenerations.
"""
from django.http import JsonResponse
from django.urls import include, path


def healthz(_request):
    return JsonResponse({"status": "ok"})


urlpatterns = [
    path("healthz", healthz, name="healthz"),
${includes.join('\n')}
]
`

  const dest = path.join(outputDir, 'backend', 'config', 'urls.py')
  await mkdir(path.dirname(dest), { recursive: true })
  await writeFile(dest, content, 'utf-8')
  return dest
}

async function exists(p: string): Promise<boolean> {
  try {
    await access(p)
    return true
  } catch {
    return false
  }
}
